import { chromium } from 'playwright';
const browser = await chromium.connectOverCDP('http://localhost:9225');
const context = browser.contexts()[0];
const page = context.pages()[0];
await page.reload();
await page.waitForTimeout(4000);
await page.click('text=Agent Hub');
await page.waitForTimeout(2000);
await page.screenshot({ path: '/Users/macbook/agent_studio_fixed.png' });
await browser.close();
