//! Routes module

pub mod approvals;
pub mod auth;
pub mod billing_webhooks;
pub mod costs;
pub mod deployments;
pub mod dispatch_handoff;
pub mod gizzi_instances;
pub mod health;
pub mod hosted_entitlements;
pub mod hosted_runtimes;
pub mod instances;
pub mod jobs;
pub mod mesh;
pub mod mirror;
pub mod mirror_ws;
pub mod providers;
pub mod regions;
pub mod runs;
pub mod runtime_pairing;
pub mod runtime_relay;
pub mod schedules;
pub mod tasks;
pub mod wizard;
