name: gizzi

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  gizzi:
    if: |
      contains(github.event.comment.body, ' /gz') ||
      startsWith(github.event.comment.body, '/gz') ||
      contains(github.event.comment.body, ' /gizzi') ||
      startsWith(github.event.comment.body, '/gizzi')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run gizzi-code
        uses: ./github
        env:
          GIZZI_API_KEY: ${{ secrets.GIZZI_API_KEY }}
          GIZZI_PERMISSION: '{"bash": "deny"}'
        with:
          model: anthropic/claude-opus-4-5
