/**
 * Allternit Code Compiler
 * 
 * Translates OpenUI Lang + Design.md Tokens into 
 * production-ready React + Tailwind CSS code.
 */

import { DesignTokens } from '../openui/design-md-parser';

interface UINode {
  tag: string;
  props: Record<string, string>;
  children: UINode[];
}

function parseOpenUI(stream: string): UINode[] {
  let pos = 0;
  
  function parseNode(): UINode | null {
    const node: UINode = { tag: '', props: {}, children: [] };
    
    // skip whitespace
    while (stream[pos] && stream[pos].trim() === '') pos++;
    
    if (stream[pos] !== '[') return null;
    pos++; // skip '['
    
    // get tag
    const tagMatch = stream.substring(pos).match(/^v:[a-zA-Z0-9-]+/);
    if (!tagMatch) return null;
    node.tag = tagMatch[0];
    pos += node.tag.length;
    
    // parse props and children
    while (pos < stream.length) {
      while (stream[pos] && stream[pos].trim() === '') pos++;
      
      if (stream[pos] === ']') {
        pos++;
        break;
      }
      
      if (stream[pos] === '[') {
        const child = parseNode();
        if (child) node.children.push(child);
      } else {
        // parse prop
        const propMatch = stream.substring(pos).match(/^([a-zA-Z0-9-]+)="([^"]*)"/);
        if (propMatch) {
          node.props[propMatch[1]] = propMatch[2];
          pos += propMatch[0].length;
        } else {
          // fallback, just advance
          pos++;
        }
      }
    }
    
    return node;
  }
  
  const nodes: UINode[] = [];
  while (pos < stream.length) {
    const node = parseNode();
    if (node) nodes.push(node);
    else pos++;
  }
  return nodes;
}

export function compileToReact(uiStream: string, tokens: DesignTokens): string {
  const primaryColor = tokens.colors.primary;
  const borderRadius = tokens.radii.base || tokens.radii.card || '8px';
  const fontFamily = tokens.typography.fontFamily.split(',')[0].replace(/"/g, '');

  let code = `import React from 'react';\n\n`;
  code += `/**\n * Generated by Allternit Design Engine\n * Brand: ${tokens.metadata.brandName}\n */\n`;
  code += `export default function GeneratedLayout() {\n`;
  code += `  return (\n`;
  code += `    <div className="min-h-screen p-8 bg-[#0a0a0a] text-white" style={{ fontFamily: '${fontFamily}' }}>\n`;

  const nodes = parseOpenUI(uiStream);

  function generateNodeCode(node: UINode, indentLevel: number): string {
    let result = '';
    const indent = '  '.repeat(indentLevel);
    
    if (node.tag === 'v:stack') {
      result += `${indent}<div className="flex flex-col gap-6 w-full max-w-4xl mx-auto">\n`;
      for (const child of node.children) {
        result += generateNodeCode(child, indentLevel + 1);
      }
      result += `${indent}</div>\n`;
    } else if (node.tag === 'v:card') {
      const title = node.props.title || 'Panel';
      result += `${indent}<div className="p-8 rounded-[${borderRadius}] border border-white/10 bg-white/5 backdrop-blur-md">\n`;
      result += `${indent}  <h3 className="text-xl font-bold mb-6" style={{ color: '${primaryColor}' }}>${title}</h3>\n`;
      for (const child of node.children) {
        result += generateNodeCode(child, indentLevel + 1);
      }
      result += `${indent}</div>\n`;
    } else if (node.tag === 'v:grid') {
      result += `${indent}<div className="grid grid-cols-1 md:grid-cols-2 gap-4">\n`;
      for (const child of node.children) {
        result += generateNodeCode(child, indentLevel + 1);
      }
      result += `${indent}</div>\n`;
    } else if (node.tag === 'v:metric') {
      const label = node.props.label || 'Metric';
      const val = node.props.val || '0';
      result += `${indent}<div className="p-4 rounded-xl bg-white/5 border border-white/5">\n`;
      result += `${indent}  <div className="text-[10px] uppercase opacity-40 font-bold mb-1">${label}</div>\n`;
      result += `${indent}  <div className="text-2xl font-black">${val}</div>\n`;
      result += `${indent}</div>\n`;
    } else if (node.tag === 'v:button') {
      const label = node.props.label || 'Action';
      result += `${indent}<button className="px-6 py-2 rounded-lg font-bold transition-all hover:scale-[1.02]" style={{ backgroundColor: '${primaryColor}', color: '#000' }}>\n`;
      result += `${indent}  ${label}\n`;
      result += `${indent}</button>\n`;
    } else {
      // Default fallback for unknown tags
      result += `${indent}<div className="p-4 border border-dashed border-white/20">\n`;
      result += `${indent}  <div>Unknown component: ${node.tag}</div>\n`;
      for (const child of node.children) {
        result += generateNodeCode(child, indentLevel + 1);
      }
      result += `${indent}</div>\n`;
    }

    return result;
  }

  for (const node of nodes) {
    code += generateNodeCode(node, 3);
  }

  code += `    </div>\n  );\n}\n`;

  return code;
}
