/**
 * Vercel Labs json-render Adapter
 * 
 * Converts between Allternit-IX UI IR and Vercel Labs json-render format.
 * 
 * json-render is a declarative UI format where components are expressed as JSON.
 * This adapter enables Allternit-IX to render UIs generated by LLMs trained on
 * json-render patterns.
 * 
 * @see https://github.com/vercel-labs/json-render
 */

import type { UIRoot, UIComponent, UIState, UIAction, ActionHandler } from '../types';

/**
 * json-render node format
 */
export interface JsonRenderNode {
  /** Component type */
  type: string;
  /** Component props */
  props?: Record<string, unknown>;
  /** Child nodes */
  children?: JsonRenderNode[];
  /** Text content (for text nodes) */
  text?: string;
}

/**
 * json-render component registry entry
 */
export interface JsonRenderComponent {
  /** Component name */
  name: string;
  /** React component or element type */
  component: string;
  /** Prop mapping (json-render prop -> component prop) */
  propMapping?: Record<string, string>;
  /** Transform props before passing */
  transformProps?: (props: Record<string, unknown>) => Record<string, unknown>;
  /** Whether component accepts children */
  acceptsChildren?: boolean;
}

/**
 * json-render schema
 */
export interface JsonRenderSchema {
  /** Schema version */
  version: string;
  /** Component tree */
  root: JsonRenderNode;
  /** State definitions */
  state?: Record<string, {
    type: 'string' | 'number' | 'boolean' | 'array' | 'object';
    default?: unknown;
  }>;
  /** Event handlers */
  events?: Record<string, {
    type: string;
    target?: string;
    payload?: unknown;
  }>;
}

/**
 * Custom handler function type
 */
export type CustomHandlerFn = (
  context: {
    state: Record<string, unknown>;
    params?: Record<string, unknown>;
    event?: unknown;
  }
) => void | Promise<void>;

/**
 * Handler registry entry metadata
 */
export interface HandlerRegistryEntry {
  /** Handler name/identifier */
  name: string;
  /** Handler function */
  handler: CustomHandlerFn;
  /** Handler description */
  description?: string;
  /** Handler version */
  version?: string;
  /** Handler tags for discovery */
  tags?: string[];
  /** Input schema for validation */
  inputSchema?: Record<string, unknown>;
  /** Output schema */
  outputSchema?: Record<string, unknown>;
}

/**
 * Global handler registry for custom action handlers
 * 
 * GAP-59: Custom Handler System
 * Implements a singleton registry for dynamic handler registration
 */
class HandlerRegistry {
  private handlers = new Map<string, HandlerRegistryEntry>();
  private tagsIndex = new Map<string, Set<string>>();

  /**
   * Register a custom handler
   * @param entry Handler registry entry
   */
  register(entry: HandlerRegistryEntry): void {
    if (!entry.name || typeof entry.handler !== 'function') {
      throw new Error('Handler must have a name and a function');
    }

    // Store handler
    this.handlers.set(entry.name, entry);

    // Index by tags
    if (entry.tags) {
      for (const tag of entry.tags) {
        if (!this.tagsIndex.has(tag)) {
          this.tagsIndex.set(tag, new Set());
        }
        this.tagsIndex.get(tag)!.add(entry.name);
      }
    }
  }

  /**
   * Unregister a handler
   * @param name Handler name
   */
  unregister(name: string): boolean {
    const entry = this.handlers.get(name);
    if (!entry) return false;

    // Remove from tags index
    if (entry.tags) {
      for (const tag of entry.tags) {
        this.tagsIndex.get(tag)?.delete(name);
      }
    }

    return this.handlers.delete(name);
  }

  /**
   * Get a handler by name
   * @param name Handler name
   */
  get(name: string): HandlerRegistryEntry | undefined {
    return this.handlers.get(name);
  }

  /**
   * Check if a handler exists
   * @param name Handler name
   */
  has(name: string): boolean {
    return this.handlers.has(name);
  }

  /**
   * Execute a handler by name
   * @param name Handler name
   * @param context Execution context
   */
  async execute(
    name: string,
    context: { state: Record<string, unknown>; params?: Record<string, unknown>; event?: unknown }
  ): Promise<void> {
    const entry = this.handlers.get(name);
    if (!entry) {
      throw new Error(`Handler not found: ${name}`);
    }

    await entry.handler(context);
  }

  /**
   * GAP-61: Handler Discovery
   * Find handlers by tags
   * @param tags Tags to search for
   */
  findByTags(tags: string[]): HandlerRegistryEntry[] {
    const matchingNames = new Set<string>();
    
    for (const tag of tags) {
      const names = this.tagsIndex.get(tag);
      if (names) {
        for (const name of names) {
          matchingNames.add(name);
        }
      }
    }

    return Array.from(matchingNames)
      .map(name => this.handlers.get(name)!)
      .filter(Boolean);
  }

  /**
   * GAP-61: Handler Discovery
   * Search handlers by name pattern or description
   * @param query Search query
   */
  search(query: string): HandlerRegistryEntry[] {
    const lowerQuery = query.toLowerCase();
    return Array.from(this.handlers.values()).filter(entry => 
      entry.name.toLowerCase().includes(lowerQuery) ||
      entry.description?.toLowerCase().includes(lowerQuery) ||
      entry.tags?.some(tag => tag.toLowerCase().includes(lowerQuery))
    );
  }

  /**
   * Get all registered handlers
   */
  listAll(): HandlerRegistryEntry[] {
    return Array.from(this.handlers.values());
  }

  /**
   * Get all available tags
   */
  getAllTags(): string[] {
    return Array.from(this.tagsIndex.keys());
  }

  /**
   * Clear all handlers
   */
  clear(): void {
    this.handlers.clear();
    this.tagsIndex.clear();
  }

  /**
   * Get registry statistics
   */
  getStats(): { total: number; tags: number } {
    return {
      total: this.handlers.size,
      tags: this.tagsIndex.size,
    };
  }
}

/** Global handler registry instance */
export const globalHandlerRegistry = new HandlerRegistry();

/**
 * GAP-60: Replace Placeholder Handlers
 * Create an action handler from json-render event config
 */
function createActionHandlerFromEvent(
  config: NonNullable<JsonRenderSchema['events']>[string]
): ActionHandler {
  switch (config.type) {
    case 'setState':
      return {
        type: 'setState',
        path: config.target || '',
        value: { $path: 'event.value' },
      };
    case 'emit':
      return {
        type: 'emitEvent',
        name: config.target || '',
        payload: config.payload as import('../types').Expression,
      };
    case 'navigate':
      return {
        type: 'navigate',
        to: config.target || '',
      };
    case 'validate':
      return {
        type: 'validate',
        paths: config.target?.split(',') || [],
      };
    default:
      // GAP-60: Custom handlers - lookup in registry or create named reference
      if (config.target && globalHandlerRegistry.has(config.target)) {
        return {
          type: 'custom',
          fn: config.target,
        };
      }
      
      // Create a reference to a custom handler that can be resolved at runtime
      return {
        type: 'custom',
        fn: config.target || `handler_${generateId()}`,
      };
  }
}

/**
 * Convert Allternit-IX UIRoot to json-render format
 */
export function convertToJsonRender(root: UIRoot): JsonRenderSchema {
  return {
    version: root.version,
    root: {
      type: 'Fragment',
      children: root.components.map(convertComponentToJsonRender),
    },
    state: convertStateToJsonRender(root.state),
    events: convertActionsToJsonRender(root.actions),
  };
}

/**
 * Convert Allternit-IX UIComponent to json-render node
 */
function convertComponentToJsonRender(component: UIComponent): JsonRenderNode {
  const node: JsonRenderNode = {
    type: component.type,
  };

  // Convert props
  if (component.props && Object.keys(component.props).length > 0) {
    node.props = { ...component.props };
  }

  // Convert bindings to props
  if (component.bindings) {
    node.props = node.props || {};
    component.bindings.forEach((binding) => {
      if (binding.direction === 'two-way') {
        // json-render uses onChange for two-way bindings
        node.props![`on${capitalize(binding.prop)}Change`] = {
          $action: 'setState',
          path: binding.statePath,
        };
      } else {
        // One-way binding
        node.props![binding.prop] = { $state: binding.statePath };
      }
    });
  }

  // Convert events to props
  if (component.events) {
    node.props = node.props || {};
    component.events.forEach((event) => {
      node.props![event.event] = {
        $action: event.action,
        params: event.params,
      };
    });
  }

  // Convert children
  if (component.children && component.children.length > 0) {
    node.children = component.children.map(convertComponentToJsonRender);
  }

  // Convert repeat to children with mapping
  if (component.repeat) {
    node.props = node.props || {};
    node.props.$for = {
      items: component.repeat.items,
      as: component.repeat.as,
      index: component.repeat.indexAs,
      filter: component.repeat.filter,
      sort: component.repeat.sort,
    };
  }

  // Convert condition
  if (component.condition) {
    node.props = node.props || {};
    node.props.$if = component.condition;
  }

  // Convert style
  if (component.style) {
    node.props = node.props || {};
    node.props.style = component.style;
  }

  // Convert className
  if (component.className) {
    node.props = node.props || {};
    node.props.className = component.className;
  }

  return node;
}

/**
 * Convert Allternit-IX state to json-render state
 */
function convertStateToJsonRender(state: UIState): JsonRenderSchema['state'] {
  const result: JsonRenderSchema['state'] = {};

  state.variables.forEach((variable) => {
    result![variable.path] = {
      type: variable.type === 'any' ? 'string' : variable.type,
      default: variable.default,
    };
  });

  return result;
}

/**
 * Convert Allternit-IX actions to json-render events
 */
function convertActionsToJsonRender(actions: UIAction[]): JsonRenderSchema['events'] {
  const result: JsonRenderSchema['events'] = {};

  actions.forEach((action) => {
    switch (action.handler.type) {
      case 'setState':
        result![action.id] = {
          type: 'setState',
          target: action.handler.path,
        };
        break;
      case 'emitEvent':
        result![action.id] = {
          type: 'emit',
          target: action.handler.name,
          payload: action.handler.payload,
        };
        break;
      case 'navigate':
        result![action.id] = {
          type: 'navigate',
          target: action.handler.to,
        };
        break;
      case 'validate':
        result![action.id] = {
          type: 'validate',
          target: action.handler.paths.join(','),
        };
        break;
      case 'custom':
        // GAP-60: Use the actual custom handler function reference
        result![action.id] = {
          type: 'custom',
          target: action.handler.fn,
        };
        break;
    }
  });

  return result;
}

/**
 * Convert json-render format to Allternit-IX UIRoot
 */
export function convertFromJsonRender(schema: JsonRenderSchema): UIRoot {
  return {
    version: schema.version,
    components: convertJsonRenderNodeToComponent(schema.root),
    state: convertJsonRenderStateToState(schema.state || {}),
    actions: convertJsonRenderEventsToActions(schema.events || {}),
  };
}

/**
 * Convert json-render node to Allternit-IX UIComponent(s)
 */
function convertJsonRenderNodeToComponent(node: JsonRenderNode): UIComponent[] {
  // Handle Fragment wrapper
  if (node.type === 'Fragment' && node.children) {
    return node.children.map((child) => convertSingleNodeToComponent(child));
  }

  return [convertSingleNodeToComponent(node)];
}

/**
 * Convert single json-render node to Allternit-IX UIComponent
 */
function convertSingleNodeToComponent(node: JsonRenderNode): UIComponent {
  const component: UIComponent = {
    id: generateId(),
    type: node.type,
    props: {},
  };

  if (node.props) {
    // Extract special props
    const { $for, $if, style, className, ...regularProps } = node.props;

    // Regular props
    component.props = regularProps as Record<string, unknown>;

    // Style
    if (style) {
      component.style = style as Record<string, string | number>;
    }

    // ClassName
    if (className) {
      component.className = className as string;
    }

    // Convert bindings from props with $state
    Object.entries(regularProps).forEach(([key, value]) => {
      if (typeof value === 'object' && value !== null && '$state' in value) {
        component.bindings = component.bindings || [];
        component.bindings.push({
          prop: key,
          statePath: (value as { $state: string }).$state,
          direction: 'one-way',
        });
        delete component.props![key];
      }
    });

    // Convert for/repeat
    if ($for) {
      const forObj = $for as { items: string; as: string; index?: string; filter?: unknown; sort?: unknown };
      component.repeat = {
        items: forObj.items,
        as: forObj.as,
        indexAs: forObj.index,
        filter: forObj.filter as import('../types').Expression,
        sort: forObj.sort as import('../types').Expression,
      };
    }

    // Convert condition
    if ($if) {
      component.condition = $if as unknown as import('../types').Expression;
    }

    // Convert event handlers
    Object.entries(regularProps).forEach(([key, value]) => {
      if (typeof value === 'object' && value !== null && '$action' in value) {
        component.events = component.events || [];
        component.events.push({
          event: key,
          action: (value as { $action: string }).$action,
          params: (value as { params?: Record<string, unknown> }).params,
        });
        delete component.props![key];
      }
    });
  }

  // Convert children
  if (node.children) {
    component.children = node.children.map(convertSingleNodeToComponent);
  }

  // Text content
  if (node.text) {
    component.props = component.props || {};
    component.props.children = node.text;
  }

  return component;
}

/**
 * Convert json-render state to Allternit-IX UIState
 */
function convertJsonRenderStateToState(
  state: NonNullable<JsonRenderSchema['state']>
): UIState {
  return {
    variables: Object.entries(state).map(([path, config]) => ({
      path,
      type: config.type,
      default: config.default,
    })),
    computed: [],
    initial: Object.entries(state).reduce((acc, [path, config]) => {
      if (config.default !== undefined) {
        acc[path] = config.default;
      }
      return acc;
    }, {} as Record<string, unknown>),
  };
}

/**
 * Convert json-render events to Allternit-IX UIActions
 * 
 * GAP-60: Replace Placeholder Handlers
 * Uses createActionHandlerFromEvent for proper handler resolution
 */
function convertJsonRenderEventsToActions(
  events: NonNullable<JsonRenderSchema['events']>
): UIAction[] {
  return Object.entries(events).map(([id, config]) => {
    const action: UIAction = {
      id,
      type: config.type as 'setState' | 'emitEvent' | 'navigate' | 'validate' | 'custom',
      handler: createActionHandlerFromEvent(config),
    };

    // Refine action type based on handler type
    if (action.handler.type === 'setState') {
      action.type = 'setState';
    } else if (action.handler.type === 'emitEvent') {
      action.type = 'emitEvent';
    } else if (action.handler.type === 'navigate') {
      action.type = 'navigate';
    } else if (action.handler.type === 'validate') {
      action.type = 'validate';
    } else if (action.handler.type === 'custom') {
      action.type = 'custom';
    }

    return action;
  });
}

/**
 * Generate unique ID
 */
function generateId(): string {
  return `comp_${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Capitalize string
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * json-render adapter configuration
 */
export const jsonRenderAdapter = {
  name: 'json-render',
  version: '1.0.0',

  /**
   * Standard json-render components mapped to Allternit-IX catalog
   */
  components: {
    // Layout
    Box: 'layout',
    Stack: 'layout',
    Grid: 'layout',
    Flex: 'layout',
    Container: 'layout',

    // Typography
    Text: 'typography',
    Heading: 'typography',
    Paragraph: 'typography',
    Label: 'typography',
    Link: 'typography',

    // Input
    Input: 'input',
    TextArea: 'input',
    Select: 'input',
    Checkbox: 'input',
    Radio: 'input',
    Switch: 'input',
    Slider: 'input',
    DatePicker: 'input',
    FileInput: 'input',

    // Display
    Image: 'display',
    Icon: 'display',
    Badge: 'display',
    Card: 'display',
    List: 'display',
    Table: 'display',
    Tabs: 'display',
    Accordion: 'display',
    Modal: 'display',
    Tooltip: 'display',
    Progress: 'display',
    Chart: 'display',
    Avatar: 'display',
    Divider: 'display',
    Spacer: 'display',
  } as Record<string, string>,

  /**
   * Convert from json-render
   */
  fromJsonRender: convertFromJsonRender,

  /**
   * Convert to json-render
   */
  toJsonRender: convertToJsonRender,

  /**
   * Check if value is a valid json-render schema
   */
  isValidSchema(value: unknown): value is JsonRenderSchema {
    if (!value || typeof value !== 'object') return false;
    const schema = value as Partial<JsonRenderSchema>;
    return (
      typeof schema.version === 'string' &&
      schema.root !== undefined &&
      typeof schema.root.type === 'string'
    );
  },

  /**
   * Check if node is a valid json-render node
   */
  isValidNode(value: unknown): value is JsonRenderNode {
    if (!value || typeof value !== 'object') return false;
    const node = value as Partial<JsonRenderNode>;
    return typeof node.type === 'string';
  },

  /**
   * GAP-59/61: Handler Registry Access
   * Get the global handler registry for custom action handlers
   */
  get handlerRegistry() {
    return globalHandlerRegistry;
  },

  /**
   * GAP-60: Execute custom handler
   * Execute a registered custom handler by name
   */
  async executeHandler(
    name: string,
    context: { state: Record<string, unknown>; params?: Record<string, unknown>; event?: unknown }
  ): Promise<void> {
    return globalHandlerRegistry.execute(name, context);
  },
};
