/**
 * Office Binding Model — canonical schema for the Office document ↔ Allternit
 * workspace relationship, per OFFICE_PRODUCTION_ARCHITECTURE.md §"Required
 * Backend Contracts".
 *
 * This module is the shared contract: the add-in taskpane uses the local
 * store today, and the backend (cmd/allternit-api office routes) should
 * persist the same shapes server-side so the platform companion and the
 * taskpane see one binding record per Office document.
 */

import { z } from 'zod'

// ── OfficeBinding ────────────────────────────────────────────────────────────

export const OFFICE_HOSTS = ['word', 'excel', 'powerpoint'] as const
export const officeHostSchema = z.enum(OFFICE_HOSTS)
export type OfficeHost = z.infer<typeof officeHostSchema>

export const officeBindingSchema = z.object({
  bindingId: z.string().min(1),
  userId: z.string().min(1),
  organizationId: z.string().nullable().default(null),
  officeHost: officeHostSchema,
  /** Stable Office-side identity when available (else a generated fallback). */
  documentExternalId: z.string().min(1),
  documentTitle: z.string().default(''),
  workspaceId: z.string().min(1),
  projectId: z.string().nullable().default(null),
  activeSessionId: z.string().nullable().default(null),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})
export type OfficeBinding = z.infer<typeof officeBindingSchema>

// ── OfficeRuntimeSession ─────────────────────────────────────────────────────

export const officeSessionEventSchema = z.object({
  at: z.string().datetime(),
  type: z.enum(['task', 'tool', 'artifact', 'approval', 'question', 'error', 'note']),
  summary: z.string(),
  detail: z.unknown().optional(),
})
export type OfficeSessionEvent = z.infer<typeof officeSessionEventSchema>

export const officeRuntimeSessionSchema = z.object({
  sessionId: z.string().min(1),
  bindingId: z.string().min(1),
  currentTask: z.string().nullable().default(null),
  /** Tool/activity timeline, oldest first. */
  timeline: z.array(officeSessionEventSchema).default([]),
  /** Last known host context (active sheet/selection/document stats). */
  hostContext: z.record(z.unknown()).default({}),
  /** Artifact ids generated by this session. */
  artifactIds: z.array(z.string()).default([]),
  /** Approvals/questions waiting on the user. */
  pendingApprovals: z
    .array(z.object({ id: z.string(), prompt: z.string(), at: z.string().datetime() }))
    .default([]),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})
export type OfficeRuntimeSession = z.infer<typeof officeRuntimeSessionSchema>

// ── Factories ────────────────────────────────────────────────────────────────

function nowIso(): string {
  return new Date().toISOString()
}

export function createOfficeBinding(input: {
  userId: string
  officeHost: OfficeHost
  documentExternalId: string
  workspaceId: string
  organizationId?: string | null
  projectId?: string | null
  documentTitle?: string
}): OfficeBinding {
  const at = nowIso()
  return officeBindingSchema.parse({
    bindingId: crypto.randomUUID(),
    organizationId: input.organizationId ?? null,
    projectId: input.projectId ?? null,
    documentTitle: input.documentTitle ?? '',
    activeSessionId: null,
    createdAt: at,
    updatedAt: at,
    ...input,
  })
}

export function createOfficeRuntimeSession(input: { bindingId: string }): OfficeRuntimeSession {
  const at = nowIso()
  return officeRuntimeSessionSchema.parse({
    sessionId: crypto.randomUUID(),
    bindingId: input.bindingId,
    createdAt: at,
    updatedAt: at,
  })
}

// ── Local binding store (taskpane half) ──────────────────────────────────────
//
// One binding per (userId, officeHost, documentExternalId). Backed by
// Office.settings when available (survives document reopen) and localStorage
// otherwise. Server persistence swaps in behind the same interface later.

export interface OfficeBindingStore {
  get(host: OfficeHost, documentExternalId: string): OfficeBinding | null
  upsert(binding: OfficeBinding): OfficeBinding
}

const STORE_KEY = 'allternit.office.bindings.v1'

// Non-browser environments (tests, SSR) have no localStorage; keep the
// store process-local there instead of silently dropping it.
const memoryFallback = new Map<string, string>()

function storageGet(key: string): string | null {
  try {
    return globalThis.localStorage?.getItem(key) ?? memoryFallback.get(key) ?? null
  } catch {
    return memoryFallback.get(key) ?? null
  }
}

function storageSet(key: string, value: string): void {
  memoryFallback.set(key, value)
  try {
    globalThis.localStorage?.setItem(key, value)
  } catch {
    // localStorage unavailable — the in-memory copy already covers it.
  }
}

/** Test hook: clears both localStorage and the in-memory fallback. */
export function __resetOfficeBindingStoreForTests(): void {
  memoryFallback.clear()
  try {
    globalThis.localStorage?.removeItem(STORE_KEY)
  } catch {
    // ignore
  }
}

function readAll(): Record<string, OfficeBinding> {
  try {
    const raw = storageGet(STORE_KEY)
    if (!raw) return {}
    const parsed = JSON.parse(raw) as Record<string, unknown>
    const out: Record<string, OfficeBinding> = {}
    for (const [key, value] of Object.entries(parsed)) {
      const result = officeBindingSchema.safeParse(value)
      if (result.success) out[key] = result.data
    }
    return out
  } catch {
    return {}
  }
}

function writeAll(bindings: Record<string, OfficeBinding>): void {
  storageSet(STORE_KEY, JSON.stringify(bindings))
}

function storeKey(host: OfficeHost, documentExternalId: string): string {
  return `${host}:${documentExternalId}`
}

export function createLocalBindingStore(): OfficeBindingStore {
  return {
    get(host, documentExternalId) {
      return readAll()[storeKey(host, documentExternalId)] ?? null
    },
    upsert(binding) {
      const all = readAll()
      const next = { ...binding, updatedAt: nowIso() }
      all[storeKey(binding.officeHost, binding.documentExternalId)] = next
      writeAll(all)
      return next
    },
  }
}

/** Get-or-create the binding for a document (stable bindingId across opens). */
export function ensureOfficeBinding(
  store: OfficeBindingStore,
  input: Parameters<typeof createOfficeBinding>[0],
): OfficeBinding {
  const existing = store.get(input.officeHost, input.documentExternalId)
  if (existing) return existing
  return store.upsert(createOfficeBinding(input))
}
