import { AllternitClient } from "./client";
import { getRepoContext, getFileContent, createPullRequest } from "./github";
import { ActionResult } from "./types";
import { readFile } from "fs/promises";

/**
 * Determines the generation task from the target input and delegates
 * to the appropriate handler (test generation, documentation, or general code).
 * @param client - The Allternit API client
 * @param target - The target file path or generation instruction
 * @returns The action result with generated code summary
 */
export async function generateCode(
  client: AllternitClient,
  target: string
): Promise<ActionResult> {
  const ctx = getRepoContext();

  if (!target) {
    return {
      success: false,
      result: "No target specified. Provide a file path or generation instruction.",
      summary: "Missing target",
    };
  }

  try {
    // Determine generation type from target
    const isTestGeneration = target.toLowerCase().includes("test");
    const isDocGeneration = target.toLowerCase().includes("doc") || target.toLowerCase().includes("readme");

    let context: string;
    let prompt: string;

    if (target.startsWith("/") || target.includes(".")) {
      // Target is a file path — read it from the repo or local filesystem
      context = await readTargetFile(ctx, target);
      prompt = isTestGeneration
        ? `Generate comprehensive unit tests for this file. Use the standard testing framework for the language.`
        : isDocGeneration
          ? `Generate detailed documentation for this file, including function descriptions, parameters, return values, and usage examples.`
          : `Improve and extend this code following best practices.`;
    } else {
      // Target is a free-form instruction
      context = `Repository: ${ctx.owner}/${ctx.repo}`;
      prompt = target;
    }

    const generated = await client.generateCode(context, prompt);

    // Extract the code block from the response
    const codeBlockMatch = generated.match(/```[\w]*\n([\s\S]*?)```/);
    const codeContent = codeBlockMatch ? codeBlockMatch[1].trim() : generated;

    return {
      success: true,
      result: codeContent,
      summary: buildGenerationSummary(target, codeContent, isTestGeneration, isDocGeneration),
    };
  } catch (error) {
    const msg = error instanceof Error ? error.message : "Unknown error";
    return {
      success: false,
      result: `Generation failed: ${msg}`,
      summary: `Generation failed: ${msg}`,
    };
  }
}

/**
 * Reads a target file from the repository or local filesystem.
 * Tries the repository API first, then falls back to local file read.
 * @param ctx - Repository context
 * @param target - File path to read
 * @returns The file content as a string
 */
async function readTargetFile(
  ctx: { owner: string; repo: string; sha?: string; ref?: string },
  target: string
): Promise<string> {
  // Try reading from the repository via GitHub API
  const ref = ctx.sha ?? ctx.ref ?? "main";
  try {
    return await getFileContent(ctx.owner, ctx.repo, target, ref);
  } catch {
    // Fall back to local filesystem
    try {
      return await readFile(target, "utf8");
    } catch {
      throw new Error(
        `Could not read file '${target}' from repository or local filesystem`
      );
    }
  }
}

/**
 * Creates a pull request with the generated code.
 * Creates a new branch, commits the generated file, and opens a PR.
 * @param client - The Allternit API client
 * @param target - Target file path for the generated code
 * @param code - The generated code content
 * @param title - PR title
 * @returns The PR number if created successfully
 */
export async function createGenerationPR(
  client: AllternitClient,
  target: string,
  code: string,
  title: string
): Promise<number | undefined> {
  const ctx = getRepoContext();
  if (!ctx.owner || !ctx.repo) {
    return undefined;
  }

  const branchName = `gizzi/generated-${Date.now()}`;
  const baseBranch = ctx.ref?.replace("refs/heads/", "") ?? "main";

  try {
    const prNumber = await createPullRequest(
      ctx.owner,
      ctx.repo,
      title,
      `Generated by Gizzi Code.\n\nTarget: \`${target}\`\n\n---\n\n\`\`\`\n${code.substring(0, 500)}${code.length > 500 ? "\n..." : ""}\n\`\`\``,
      branchName,
      baseBranch
    );
    return prNumber;
  } catch (error) {
    console.error("Failed to create PR:", error);
    return undefined;
  }
}

/**
 * Builds a markdown summary for the generation result.
 * @param target - The generation target/instruction
 * @param code - The generated code
 * @param isTests - Whether this was test generation
 * @param isDocs - Whether this was documentation generation
 * @returns Markdown summary string
 */
function buildGenerationSummary(
  target: string,
  code: string,
  isTests: boolean,
  isDocs: boolean
): string {
  const type = isTests ? "Tests" : isDocs ? "Documentation" : "Code";
  const lines = code.split("\n").length;

  return [
    `## ⚡ Gizzi Code Generation — ${type}`,
    "",
    `**Target:** \`${target}\``,
    `**Generated:** ${lines} lines`,
    "",
    "### Preview",
    "```",
    code.substring(0, 1000) + (code.length > 1000 ? "\n..." : ""),
    "```",
    "",
    "_Generated by Gizzi Code by Allternit_",
  ].join("\n");
}
