use std::env;
use std::fs;
use std::path::Path;

// This build script generates JSON schemas from our Rust types
// and places them in a schemas directory for external consumption
fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Get the output directory
    let out_dir = env::var("OUT_DIR")?;
    let dest_path = Path::new(&out_dir).join("schemas");

    // Create the schemas directory if it doesn't exist
    fs::create_dir_all(&dest_path)?;

    // Also copy schemas to a more accessible location in the crate root
    let project_root = env::var("CARGO_MANIFEST_DIR")?;
    let project_schemas_path = Path::new(&project_root).join("schemas");
    fs::create_dir_all(&project_schemas_path)?;

    // For now, we'll just create placeholder files to indicate the schemas exist
    // The actual schemas will be generated by a separate tool or process
    // since build scripts can't reference the crate being built

    // Create a README file explaining the schema generation
    let readme_content = r#"# JSON Schemas

This directory contains JSON schemas for all kernel contracts.

The schemas are generated from the Rust types in the kernel-contracts crate using the `schemars` crate.

To generate the schemas, run:
```bash
cargo run --bin schema-generator
```

Or use the test in the kernel-contracts crate:
```bash
cargo test --package allternit-kernel-contracts --test schema_tests
```
"#;

    fs::write(project_schemas_path.join("README.md"), readme_content)?;

    Ok(())
}
