import json
import os
import argparse
import sys

def load_json(path):
    try:
        with open(path, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f'Error: File not found at {path}')
        sys.exit(1)
    except json.JSONDecodeError:
        print(f'Error: Invalid JSON in {path}')
        sys.exit(1)


def generate_env(profile_path, output_path):
    profile = load_json(profile_path)
    
    with open(output_path, 'w') as f:
        f.write('# Generated by A2R Gateway Config Generator\n')
        f.write(f'# Environment: {profile.get("environment", "unknown")}\n\n')
        
        # Gateway Base URL
        base_url = profile.get('base_url', 'http://localhost:8013')
        f.write(f'ALLTERNIT_GATEWAY_URL={base_url}\n')
        
        # Service Ports
        for service, config in profile.get('services', {}).items():
            port = config.get('port')
            host = config.get('host', 'localhost')
            if port:
                # Standardize env var names: ALLTERNIT_SERVICE_KERNEL_PORT
                env_var_name = f'ALLTERNIT_SERVICE_{service.upper()}_PORT'
                f.write(f'{env_var_name}={port}\n')
                
                # Also URL: ALLTERNIT_SERVICE_KERNEL_URL
                url_var_name = f'ALLTERNIT_SERVICE_{service.upper()}_URL'
                f.write(f'{url_var_name}=http://{host}:{port}\n')
                
    print(f'Successfully generated env config at {output_path}')


def generate_config(contract_path, profile_path, output_path):
    contract = load_json(contract_path)
    profile = load_json(profile_path)
    
    registry = {
        'version': contract.get('version', 'v0.1'),
        'generated_at': os.environ.get('BUILD_TIMESTAMP', 'unknown'),
        'environment': profile.get('environment', 'unknown'),
        'external_ingress': {
            'id': 'a2r-gateway',
            'protocol': 'http',
            'routes': []
        },
        'services': []
    }
    
    # 1. Generate Services from Contract + Profile
    # Contract defines *what* services exist (abstractly via routes)
    # Profile defines *where* they live (physically)
    
    # Extract unique services from contract routes
    contract_services = set()
    for route in contract.get('core_routes', []):
        contract_services.add(route['service'])
        
        # Add route
        registry['external_ingress']['routes'].append({
            'path_prefix': route['prefix'],
            'service': route['service'],
            'methods': ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'], # Default allow all for now, or parse operations
            'operations': route.get('operations', [])
        })
        
    # Generate service definitions
    for service_name in contract_services:
        service_config = profile.get('services', {}).get(service_name)
        
        internal_url = 'http://unknown-service'
        if service_config:
            host = service_config.get('host', 'localhost')
            port = service_config.get('port', 80)
            internal_url = f'http://{host}:{port}'
        else:
            print(f'Warning: No profile configuration for service \'{service_name}\'')
            
        registry['services'].append({
            'name': service_name,
            'internal_url': internal_url,
            'exposed': True # Assuming core routes are exposed
        })
        
    # Write output
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump(registry, f, indent=2)
        
    print(f'Successfully generated gateway config at {output_path}')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate A2R Gateway Config')
    parser.add_argument('--contract', help='Path to gateway-contract.json')
    parser.add_argument('--profile', required=True, help='Path to environment profile.json')
    parser.add_argument('--output', help='Output path for gateway_registry.json')
    parser.add_argument('--env-output', help='Output path for .env file')
    
    args = parser.parse_args()
    
    if args.contract and args.output:
        generate_config(args.contract, args.profile, args.output)
        
    if args.env_output:
        generate_env(args.profile, args.env_output)
