import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy — Allternit",
  description: "Privacy Policy for the Allternit platform.",
}

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section className="mb-10">
    <h2 style={{ fontFamily: 'Georgia, serif', fontWeight: 400, fontSize: 22, color: 'var(--ui-text-inverse)', marginBottom: 12 }}>
      {title}
    </h2>
    <div style={{ color: '#5A5A5A', lineHeight: 1.75, fontSize: 15 }}>{children}</div>
  </section>
)

export default function PrivacyPage() {
  return (
    <div style={{ background: '#FDF8F3', minHeight: '100vh' }}>
      {/* Nav */}
      <nav style={{ borderBottom: '1px solid #E8D9C8', padding: '0 32px', height: 56, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <a href="/" style={{ display: 'flex', alignItems: 'center', gap: 6, textDecoration: 'none' }}>
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: 18, color: '#D97757' }}>A://</span>
          <span style={{ fontFamily: 'Georgia, serif', fontSize: 18, color: 'var(--ui-text-inverse)' }}>LLTERNIT</span>
        </a>
        <a href="https://allternit.com" style={{ fontSize: 13, color: 'var(--ui-text-secondary)', textDecoration: 'none' }}>← allternit.com</a>
      </nav>

      <main style={{ maxWidth: 720, margin: '0 auto', padding: '64px 32px' }}>
        <header style={{ marginBottom: 48 }}>
          <p style={{ fontSize: 12, textTransform: 'uppercase', letterSpacing: '0.1em', color: '#D97757', marginBottom: 12 }}>
            Legal
          </p>
          <h1 style={{ fontFamily: 'Georgia, serif', fontWeight: 400, fontSize: 40, color: 'var(--ui-text-inverse)', lineHeight: 1.1, marginBottom: 16 }}>
            Privacy Policy
          </h1>
          <p style={{ color: 'var(--ui-text-secondary)', fontSize: 14 }}>Last updated: March 2026</p>
        </header>

        <Section title="1. Information We Collect">
          <p>We collect information you provide directly (account details, workspace data) and usage data generated by the Service (agent logs, API calls, session metadata). We do not collect sensitive personal information beyond what is required to operate the platform.</p>
        </Section>

        <Section title="2. How We Use Information">
          <p>We use your data to: operate and improve the Service, authenticate your account, provide customer support, and generate aggregate insights about platform usage. We do not sell your data or use it to train AI models without explicit consent.</p>
        </Section>

        <Section title="3. Agent Data & Lineage">
          <p>Allternit's Git-based agent lineage system stores a cryptographically auditable history of agent actions. This data is stored in your workspace and accessible only to you unless explicitly shared. It is used to provide auditability guarantees consistent with our Constitutional Principles.</p>
        </Section>

        <Section title="4. Data Sharing">
          <p>We do not sell or rent your personal information. We may share data with service providers (hosting, auth) under confidentiality agreements. We will disclose data when required by law.</p>
        </Section>

        <Section title="5. Data Retention">
          <p>Account data is retained for the life of your account. You may request deletion at any time. Agent lineage data is deleted within 30 days of account termination unless legally required to retain it.</p>
        </Section>

        <Section title="6. Security">
          <p>We use industry-standard encryption and access controls. The platform is designed with a minimal trust surface — agent actions are sandboxed and auditable by default.</p>
        </Section>

        <Section title="7. Your Rights">
          <p>You have the right to access, correct, export, and delete your data. Contact <a href="mailto:privacy@allternit.com" style={{ color: '#C45C26' }}>privacy@allternit.com</a> to exercise these rights.</p>
        </Section>

        <Section title="8. Contact">
          <p>Privacy questions: <a href="mailto:privacy@allternit.com" style={{ color: '#C45C26' }}>privacy@allternit.com</a></p>
        </Section>
      </main>

      <footer style={{ borderTop: '1px solid #E8D9C8', padding: '24px 32px', textAlign: 'center' }}>
        <p style={{ fontSize: 12, color: 'var(--ui-text-secondary)' }}>© 2026 Allternit PBC</p>
      </footer>
    </div>
  )
}
