/**
 * Codemap schema.
 *
 * Deterministic architecture map of a repo, generated by `gizzi init` (or
 * standalone via `gizzi codemap generate`). No LLM calls anywhere in this
 * pipeline — every field here is mechanically derived from real source
 * evidence. `confidence` is required (never optional) on every piece of
 * evidence so "never fabricate, mark unknown when unsure" is a schema-level
 * invariant, not just a convention to remember.
 */
import z from "zod/v4"

export const EdgeType = z.enum(["imports", "calls", "reads", "writes", "publishes", "subscribes"])
export type EdgeType = z.infer<typeof EdgeType>

export const Confidence = z.enum(["verified", "textual", "unknown"])
export type Confidence = z.infer<typeof Confidence>

export const Evidence = z.object({
  file: z.string(),
  line: z.number(),
  symbol: z.string().optional(),
  confidence: Confidence,
})
export type Evidence = z.infer<typeof Evidence>

export const CodemapNode = z.object({
  id: z.string(),
  path: z.string(),
  role: z.string(),
  entrypoints: z.array(z.string()),
  tests: z.array(z.string()),
  constraints: z.array(z.string()),
  evidence: z.array(Evidence),
})
export type CodemapNode = z.infer<typeof CodemapNode>

export const CodemapEdge = z.object({
  from: z.string(),
  to: z.string(),
  type: EdgeType,
  evidence: z.array(Evidence),
})
export type CodemapEdge = z.infer<typeof CodemapEdge>

export const CodemapFlow = z.object({
  trigger: z.string(),
  steps: z.array(z.string()),
  outcome: z.string(),
})
export type CodemapFlow = z.infer<typeof CodemapFlow>

export const CodemapJson = z.object({
  generated_at: z.string(),
  generated_from_commit: z.string(),
  scope: z.array(z.string()),
  nodes: z.array(CodemapNode),
  edges: z.array(CodemapEdge),
  flows: z.array(CodemapFlow),
})
export type CodemapJson = z.infer<typeof CodemapJson>

export const CodemapLockModule = z.object({
  fingerprint: z.string(),
  file_count: z.number(),
})
export type CodemapLockModule = z.infer<typeof CodemapLockModule>

export const CodemapLock = z.object({
  commit: z.string(),
  dirty: z.boolean(),
  generated_at: z.string(),
  scope: z.array(z.string()),
  excluded: z.array(z.string()),
  fingerprint_algorithm: z.literal("sha256-tracked-paths-plus-contents-v1"),
  modules: z.record(z.string(), CodemapLockModule),
})
export type CodemapLock = z.infer<typeof CodemapLock>

/** A discovered primary module/node, before edges/flows are computed. */
export interface DiscoveredModule {
  id: string
  path: string
  role: string
  fileCount: number
}

/** A file-level edge before roll-up to node-level (see edges.ts). */
export interface FileEdge {
  fromFile: string
  toFile: string
  type: EdgeType
  evidence: Evidence
}

export interface GenerateCodemapResult {
  ok: boolean
  reason?: string
  staleModules: string[]
  /** The assembled codemap, present whenever ok is true. Lets callers (e.g.
   * `gizzi codemap generate --vault-export`) reuse the already-validated
   * data without a redundant re-read of codemap.json from disk. */
  codemap?: CodemapJson
}
