/**
 * Codemap → Vault export: writes the deterministic codemap as real,
 * wikilinked Obsidian-compatible notes into the user's Vault/Brain
 * (`gizzi codemap generate --vault-export`), so the codebase's module
 * graph joins the same browsable knowledge graph as everything else
 * there — viewable in the vendored WebObsidian mini app, searchable via
 * the Lens MCP server, and picked up by `gizzi vault graph`'s own
 * indexing/semantic-linking with zero extra code, since these are just
 * plain notes with real frontmatter and [[wikilinks]].
 *
 * Opt-in only — not run by `gizzi init`'s automatic codemap step.
 *
 * Deterministic: never embeds `codemap.generated_at` (the one
 * non-deterministic field in CodemapJson) anywhere in a note body, and
 * uses the same marker-based idempotent regeneration as vault/graph/build.ts
 * so reruns on unchanged content produce byte-identical notes.
 */
import path from "path"
import * as IO from "../vault/io"
import type { Vault } from "../vault/types"
import { withAutoGeneratedSection } from "../vault/graph/markers"
import type { CodemapEdge, CodemapJson, CodemapNode } from "./types"

const AUTO_START = "<!-- gizzi-codemap:auto-generated:start -->"
const AUTO_END = "<!-- gizzi-codemap:auto-generated:end -->"

export interface VaultExportResult {
  moduleCount: number
  hubRelPath: string
  vaultRoot: string
}

function moduleTitle(repoName: string, moduleId: string): string {
  return `${repoName}/${moduleId}`
}

async function writeExportNote(
  vaultRoot: string,
  relId: string,
  title: string,
  type: Vault.EntityType,
  defaultTags: string[],
  bodyLines: string[],
): Promise<void> {
  const absPath = path.join(vaultRoot, relId)
  const existing = await IO.readNote(absPath, vaultRoot)
  const content = withAutoGeneratedSection(existing?.content ?? `## ${title}\n`, bodyLines, { start: AUTO_START, end: AUTO_END })
  const frontmatter: Vault.Frontmatter = {
    title,
    type,
    source: "codemap",
    sensitivity: "private",
    tags: existing?.frontmatter.tags?.length ? existing.frontmatter.tags : defaultTags,
  }
  await IO.writeNote(absPath, { frontmatter, content })
}

function moduleBodyLines(
  node: CodemapNode,
  repoName: string,
  outgoing: CodemapEdge[],
  incoming: CodemapEdge[],
): string[] {
  const lines: string[] = [`**Codebase:** [[${repoName}]]`, `**Path:** \`${node.path}\``, `**Role:** ${node.role}`, ""]

  lines.push("### Entrypoints")
  lines.push("")
  if (node.entrypoints.length) {
    for (const ep of node.entrypoints) lines.push(`- \`${ep}\``)
  } else {
    lines.push("_none discovered_")
  }
  lines.push("")

  lines.push("### Dependencies")
  lines.push("")
  if (outgoing.length) {
    for (const e of outgoing) lines.push(`- [[${moduleTitle(repoName, e.to)}]] (${e.type}, ${e.evidence.length} evidence)`)
  } else {
    lines.push("_none_")
  }
  lines.push("")

  lines.push("### Depended on by")
  lines.push("")
  if (incoming.length) {
    for (const e of incoming) lines.push(`- [[${moduleTitle(repoName, e.from)}]] (${e.type}, ${e.evidence.length} evidence)`)
  } else {
    lines.push("_none_")
  }

  return lines
}

function hubBodyLines(codemap: CodemapJson, repoName: string): string[] {
  const lines: string[] = [`### Modules (${codemap.nodes.length})`, ""]
  for (const node of codemap.nodes) {
    lines.push(`- [[${moduleTitle(repoName, node.id)}]] — ${node.role}`)
  }
  lines.push("")

  lines.push("### Flows")
  lines.push("")
  if (codemap.flows.length) {
    codemap.flows.forEach((flow, i) => {
      const steps = flow.steps.map((s) => `[[${moduleTitle(repoName, s)}]]`).join(" → ")
      lines.push(`${i + 1}. **Trigger:** ${flow.trigger}`)
      lines.push(`   **Steps:** ${steps}`)
      lines.push(`   **Outcome:** ${flow.outcome}`)
    })
  } else {
    lines.push("_no flows detected_")
  }

  return lines
}

export async function exportCodemapToVault(codemap: CodemapJson, repoName: string, vaultRoot: string): Promise<VaultExportResult> {
  const sanitizedRepo = IO.sanitizeFilename(repoName)
  const sortedNodes = [...codemap.nodes].sort((a, b) => a.id.localeCompare(b.id))

  const edgesByFrom = new Map<string, CodemapEdge[]>()
  const edgesByTo = new Map<string, CodemapEdge[]>()
  for (const e of codemap.edges) {
    if (!edgesByFrom.has(e.from)) edgesByFrom.set(e.from, [])
    edgesByFrom.get(e.from)!.push(e)
    if (!edgesByTo.has(e.to)) edgesByTo.set(e.to, [])
    edgesByTo.get(e.to)!.push(e)
  }

  for (const node of sortedNodes) {
    const relId = path.join("Codebase", sanitizedRepo, `${IO.sanitizeFilename(node.id)}.md`)
    const title = moduleTitle(repoName, node.id)
    const outgoing = edgesByFrom.get(node.id) ?? []
    const incoming = edgesByTo.get(node.id) ?? []
    await writeExportNote(vaultRoot, relId, title, "module", ["codemap", sanitizedRepo], moduleBodyLines(node, repoName, outgoing, incoming))
  }

  const hubRelPath = path.join("Codebase", `${sanitizedRepo}.md`)
  await writeExportNote(vaultRoot, hubRelPath, repoName, "project", ["codemap", sanitizedRepo], hubBodyLines(codemap, repoName))

  return { moduleCount: sortedNodes.length, hubRelPath, vaultRoot }
}
