// AUTO-GENERATED by scripts/build-native-plugin-catalog.mjs — do not edit by hand.
// Sources: .tmp-anthropic-skills-src/skills (Claude-native), archive/plugins (Codex workflow),
// .agents/skills (Allternit/Codex skills). Regenerate with: node scripts/build-native-plugin-catalog.mjs

import type { PluginCategory } from '@/lib/plugins/marketplace';

export type NativePluginOrigin = 'claude-native' | 'codex' | 'allternit';

export interface NativePluginCatalogEntry {
  id: string;
  name: string;
  description: string;
  version: string;
  category: PluginCategory;
  origin: NativePluginOrigin;
  tags: string[];
}

export const NATIVE_PLUGIN_CATALOG: NativePluginCatalogEntry[] = [
  {
    "id": "claude-algorithmic-art",
    "name": "Algorithmic Art",
    "description": "Creating algorithmic art using p5.js with seeded randomness and interactive parameter exploration. Use this when users request creating art using code,…",
    "version": "1.0.0",
    "category": "create",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "algorithmic-art"
    ]
  },
  {
    "id": "claude-brand-guidelines",
    "name": "Brand Guidelines",
    "description": "Applies Anthropic's official brand colors and typography to any sort of artifact that may benefit from having Anthropic's look-and-feel. Use it when brand…",
    "version": "1.0.0",
    "category": "create",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "brand-guidelines"
    ]
  },
  {
    "id": "claude-canvas-design",
    "name": "Canvas Design",
    "description": "Create beautiful visual art in .png and .pdf documents using design philosophy. You should use this skill when the user asks to create a poster, piece of art,…",
    "version": "1.0.0",
    "category": "create",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "canvas-design"
    ]
  },
  {
    "id": "claude-claude-api",
    "name": "Claude API",
    "description": "Build, debug, and optimize Claude API / Anthropic SDK apps. Apps built with this skill should include prompt caching. Also handles migrating existing Claude…",
    "version": "1.0.0",
    "category": "build",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "claude-api"
    ]
  },
  {
    "id": "claude-doc-coauthoring",
    "name": "Doc Co-Authoring",
    "description": "Guide users through a structured workflow for co-authoring documentation. Use when user wants to write documentation, proposals, technical specs, decision…",
    "version": "1.0.0",
    "category": "productivity",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "doc-coauthoring"
    ]
  },
  {
    "id": "claude-docx",
    "name": "DOCX",
    "description": "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files). Triggers include: any mention of 'Word doc', 'word…",
    "version": "1.0.0",
    "category": "productivity",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "docx"
    ]
  },
  {
    "id": "claude-frontend-design",
    "name": "Frontend Design",
    "description": "Create distinctive, production-grade frontend interfaces with high design quality. Use this skill when the user asks to build web components, pages, artifacts,…",
    "version": "1.0.0",
    "category": "create",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "frontend-design"
    ]
  },
  {
    "id": "claude-internal-comms",
    "name": "Internal Comms",
    "description": "A set of resources to help me write all kinds of internal communications, using the formats that my company likes to use. Claude should use this skill whenever…",
    "version": "1.0.0",
    "category": "productivity",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "internal-comms"
    ]
  },
  {
    "id": "claude-mcp-builder",
    "name": "MCP Builder",
    "description": "Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when…",
    "version": "1.0.0",
    "category": "build",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "mcp-builder"
    ]
  },
  {
    "id": "claude-pdf",
    "name": "PDF",
    "description": "Use this skill whenever the user wants to do anything with PDF files. This includes reading or extracting text/tables from PDFs, combining or merging multiple…",
    "version": "1.0.0",
    "category": "productivity",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "pdf"
    ]
  },
  {
    "id": "claude-pptx",
    "name": "PPTX",
    "description": "Use this skill any time a .pptx file is involved in any way — as input, output, or both. This includes: creating slide decks, pitch decks, or presentations;…",
    "version": "1.0.0",
    "category": "productivity",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "pptx"
    ]
  },
  {
    "id": "claude-skill-creator",
    "name": "Skill Creator",
    "description": "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, edit, or optimize an…",
    "version": "1.0.0",
    "category": "build",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "skill-creator"
    ]
  },
  {
    "id": "claude-slack-gif-creator",
    "name": "Slack GIF Creator",
    "description": "Knowledge and utilities for creating animated GIFs optimized for Slack. Provides constraints, validation tools, and animation concepts. Use when users request…",
    "version": "1.0.0",
    "category": "create",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "slack-gif-creator"
    ]
  },
  {
    "id": "claude-theme-factory",
    "name": "Theme Factory",
    "description": "Toolkit for styling artifacts with a theme. These artifacts can be slides, docs, reportings, HTML landing pages, etc. There are 10 pre-set themes with…",
    "version": "1.0.0",
    "category": "create",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "theme-factory"
    ]
  },
  {
    "id": "claude-web-artifacts-builder",
    "name": "Web Artifacts Builder",
    "description": "Suite of tools for creating elaborate, multi-component claude.ai HTML artifacts using modern frontend web technologies (React, Tailwind CSS, shadcn/ui). Use…",
    "version": "1.0.0",
    "category": "create",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "web-artifacts-builder"
    ]
  },
  {
    "id": "claude-webapp-testing",
    "name": "Web App Testing",
    "description": "Toolkit for interacting with and testing local web applications using Playwright. Supports verifying frontend functionality, debugging UI behavior, capturing…",
    "version": "1.0.0",
    "category": "build",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "webapp-testing"
    ]
  },
  {
    "id": "claude-xlsx",
    "name": "XLSX",
    "description": "Use this skill any time a spreadsheet file is the primary input or output. This means any task where the user wants to: open, read, edit, or fix an existing…",
    "version": "1.0.0",
    "category": "productivity",
    "origin": "claude-native",
    "tags": [
      "claude-native",
      "skill",
      "xlsx"
    ]
  },
  {
    "id": "codex-apispeccard-plugin",
    "name": "API Spec Card",
    "description": "Plugin based on APISpecCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-chatbotcard-plugin",
    "name": "Chatbot Card",
    "description": "Plugin based on ChatbotCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-codereviewcard-plugin",
    "name": "Code Review Card",
    "description": "Plugin based on CodeReviewCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-datatablecard-plugin",
    "name": "Data Table Card",
    "description": "Plugin based on DataTableCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-documentanalyzercard-plugin",
    "name": "Document Analyzer Card",
    "description": "Plugin based on DocumentAnalyzerCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-emailcomposercard-plugin",
    "name": "Email Composer Card",
    "description": "Plugin based on EmailComposerCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-imagegencard-plugin",
    "name": "Image Generator Card",
    "description": "Plugin based on ImageGenCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-iosappbuild-plugin",
    "name": "iOS App Builder",
    "description": "Build and run iOS apps from React Native, Expo, or Swift projects using xcodebuild",
    "version": "1.0.0",
    "category": "build",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-marketresearchcard-plugin",
    "name": "Market Research Card",
    "description": "Plugin based on MarketResearchCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-prdescriptioncard-plugin",
    "name": "PR Description Card",
    "description": "Plugin based on PRDescriptionCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-remotioncard-plugin",
    "name": "Remotion Video Generator",
    "description": "Generate videos from prompts using Remotion React components",
    "version": "1.0.0",
    "category": "create",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-socialmediacard-plugin",
    "name": "Social Media Card",
    "description": "Plugin based on SocialMediaCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-testgeneratorcard-plugin",
    "name": "Test Generator Card",
    "description": "Plugin based on TestGeneratorCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-translationcard-plugin",
    "name": "Translation Card",
    "description": "Plugin based on TranslationCard.tsx template",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "codex-verceldeploy-plugin",
    "name": "Vercel Deploy",
    "description": "Deploy projects to Vercel instantly via API",
    "version": "1.0.0",
    "category": "automate",
    "origin": "codex",
    "tags": [
      "codex",
      "workflow"
    ]
  },
  {
    "id": "allternit-alabs-course-pipeline",
    "name": "ALabs Course Pipeline",
    "description": "End-to-end A://Labs course creation pipeline. Creates Canvas courses, generates interactive HTML modules from Allternit packages, syncs quizzes, tracks…",
    "version": "1.0.0",
    "category": "productivity",
    "origin": "allternit",
    "tags": [
      "allternit",
      "skill",
      "alabs-course-pipeline"
    ]
  },
  {
    "id": "allternit-allternit-codebase-to-course",
    "name": "Allternit Codebase To Course",
    "description": "Turn any Allternit package or codebase into a beautiful, interactive single-page HTML course module for the A://Labs curriculum. Use this skill whenever…",
    "version": "1.0.0",
    "category": "productivity",
    "origin": "allternit",
    "tags": [
      "allternit",
      "skill",
      "allternit-codebase-to-course"
    ]
  },
  {
    "id": "codex-clone-website",
    "name": "Clone Website",
    "description": "Reverse-engineers any public website and rebuilds it as a pixel-accurate React page using the Allternit design system. Extracts computed styles, design tokens,…",
    "version": "1.0.0",
    "category": "build",
    "origin": "codex",
    "tags": [
      "codex",
      "skill",
      "clone-website"
    ]
  },
  {
    "id": "codex-mobile-app-design",
    "name": "Mobile App Design",
    "description": "Mobile app UI/UX design skill. Generates frame structures, React Native / Expo component code, asset manifests, and navigation flows. Outputs Figma-compatible…",
    "version": "1.0.0",
    "category": "create",
    "origin": "codex",
    "tags": [
      "codex",
      "skill",
      "mobile-app-design"
    ]
  }
];
