export interface PhilosophySchool {
  id: string;
  skillId: string;
  name: string;
  subtitle: string;
  era: string;
  palette: string[];
  accent: string;
  stance: string;
  tags: string[];
  /** Nearest DesignDirection id — used to pre-bind palette + posture when launching */
  directionId?: string;
}

export const PHILOSOPHY_SCHOOLS: PhilosophySchool[] = [
  {
    id: 'muji-hara',
    skillId: 'hs-muji-hara',
    directionId: 'modern-minimal',
    name: 'Muji / Kenya Hara',
    subtitle: 'Emptiness (Ma)',
    era: '1980s–present',
    palette: ['#f5f0eb', '#ede5d8', '#d4c9b8', '#8c7b6e', '#3d2e26'],
    accent: '#8c7b6e',
    stance: 'Emptiness is not absence — it is the condition of possibility. Negative space is the most loaded element on the page.',
    tags: ['japanese', 'minimal', 'emptiness', 'raw materials'],
  },
  {
    id: 'rams-braun',
    skillId: 'hs-rams-braun',
    directionId: 'tech-utility',
    name: 'Braun / Dieter Rams',
    subtitle: '10 Principles of Good Design',
    era: '1955–1995',
    palette: ['#f0ede8', '#ddd9d4', '#b8b4ae', '#6e6b66', '#2a2825'],
    accent: '#6e6b66',
    stance: 'Good design is as little design as possible. Remove until nothing remains that can be removed without breaking function.',
    tags: ['functionalism', 'industrial', 'systematic', 'honest'],
  },
  {
    id: 'pentagram-bierut',
    skillId: 'hs-pentagram-bierut',
    directionId: 'swiss-brockmann',
    name: 'Pentagram / Michael Bierut',
    subtitle: 'Typography-First Identity',
    era: '1990s–present',
    palette: ['#ffffff', '#f2f2f2', '#1a1a1a', '#cc2200', '#ff3322'],
    accent: '#cc2200',
    stance: 'Strong typographic hierarchy eliminates the need for decoration. One accent, one grid, one voice — let the letterforms carry everything.',
    tags: ['pentagram', 'swiss grid', 'typography', '60% whitespace'],
  },
  {
    id: 'sagmeister-walsh',
    skillId: 'hs-sagmeister-walsh',
    directionId: 'brutalist-experimental',
    name: 'Sagmeister & Walsh',
    subtitle: 'Emotional / Autobiographical',
    era: '1993–present',
    palette: ['#1a0a2e', '#4a1a6e', '#c84b9e', '#f5a623', '#f5f0e8'],
    accent: '#c84b9e',
    stance: 'Design that comes from somewhere — from a body, a memory, a feeling. Nothing is off-limits if it makes the viewer feel something specific.',
    tags: ['emotional', 'autobiographical', 'handmade', 'provocative'],
  },
  {
    id: 'vignelli-grid',
    skillId: 'hs-vignelli-grid',
    directionId: 'swiss-brockmann',
    name: 'Massimo Vignelli',
    subtitle: 'Grid Discipline',
    era: '1960s–2014',
    palette: ['#ffffff', '#f5f5f5', '#c8c8c8', '#222222', '#cc0000'],
    accent: '#cc0000',
    stance: 'The grid is not a prison. It is liberation from the chaos of arbitrary decisions. A few great typefaces used well will outlast any trend.',
    tags: ['helvetica', 'grid', 'timeless', 'semantic'],
  },
  {
    id: 'dumbar-systematic',
    skillId: 'hs-dumbar-systematic',
    directionId: 'content-first-ia',
    name: 'Studio Dumbar',
    subtitle: 'Systematic & Vibrant',
    era: '1977–present',
    palette: ['#ff5a1f', '#004e89', '#1a936f', '#f9c74f', '#590d22'],
    accent: '#ff5a1f',
    stance: 'Geometric systems at scale. Order and energy are not opposites — a rigorous system can radiate more vitality than expressive spontaneity.',
    tags: ['systematic', 'vibrant', 'municipal scale', 'multi-color'],
  },
  {
    id: 'jetset-selfreferential',
    skillId: 'hs-jetset-selfreferential',
    directionId: 'monogram-jetset',
    name: 'Experimental Jetset',
    subtitle: 'Self-Reference',
    era: '1997–present',
    palette: ['#ffffff', '#f0f0f0', '#aaaaaa', '#333333', '#000000'],
    accent: '#333333',
    stance: 'Design about design. The material of the work is the language of design itself — Helvetica, the grid, the offset print — made visible as subject.',
    tags: ['self-reference', 'helvetica', 'monochrome', 'conceptual'],
  },
  {
    id: 'norm-mathematical',
    skillId: 'hs-norm-mathematical',
    directionId: 'swiss-brockmann',
    name: 'Norm (Swiss)',
    subtitle: 'Mathematical Proportion',
    era: '1999–present',
    palette: ['#fafafa', '#e8e8e8', '#c4c4c4', '#585858', '#0a0a0a'],
    accent: '#585858',
    stance: 'Proportion is the only argument. Every spacing decision is derived, never chosen. Swiss discipline without the warmth of ideology.',
    tags: ['mathematical', 'proportion', 'neutral', 'rigorous'],
  },
  {
    id: 'borsche-editorial',
    skillId: 'hs-borsche-editorial',
    directionId: 'editorial-monocle',
    name: 'Bureau Borsche',
    subtitle: 'Editorial Fashion Direction',
    era: '2007–present',
    palette: ['#f5e6d0', '#e8c89a', '#c4855a', '#7a3b1e', '#1a0a00'],
    accent: '#c4855a',
    stance: 'Cultural institutions treated like luxury fashion houses. Photography cropped to provocation. Typography that belongs in a museum.',
    tags: ['editorial', 'fashion', 'photography', 'cultural'],
  },
  {
    id: 'hort-raw',
    skillId: 'hs-hort-raw',
    directionId: 'brutalist-experimental',
    name: 'Hort',
    subtitle: 'Raw Typography / Collage',
    era: '1994–present',
    palette: ['#0d0d0d', '#1c1c1c', '#2a2a2a', '#ff2d55', '#f0f0e8'],
    accent: '#ff2d55',
    stance: 'Anti-polish as a political stance. The rough edge, the cut-up, the unexpected composition — they carry urgency that no refined version can.',
    tags: ['collage', 'raw', 'berlin', 'underground'],
  },
  {
    id: 'wolff-olins',
    skillId: 'hs-wolff-olins',
    directionId: 'brutalist-experimental',
    name: 'Wolff Olins',
    subtitle: 'Brand Transformation',
    era: '1965–present',
    palette: ['#f2f2f2', '#e5e5e5', '#1c1c1e', '#ff3b30', '#007aff'],
    accent: '#ff3b30',
    stance: 'Brands are organizational change made visible. The identity that makes people uncomfortable is often the one that works.',
    tags: ['transformation', 'bold', 'strategic', 'unexpected'],
  },
  {
    id: 'nonformat-phototypo',
    skillId: 'hs-nonformat-phototypo',
    directionId: 'editorial-monocle',
    name: 'Non-Format',
    subtitle: 'Photo-Led Typography',
    era: '2000–present',
    palette: ['#fffaf0', '#f5deb3', '#d2691e', '#8b4513', '#2c1a0e'],
    accent: '#d2691e',
    stance: 'Image and type in the same compositional space — neither dominant, both contributing. Surreal combinations that reward close looking.',
    tags: ['photography', 'typographic freedom', 'collage', 'music culture'],
  },
  {
    id: 'bibliotheque-neutral',
    skillId: 'hs-bibliotheque-neutral',
    directionId: 'content-first-ia',
    name: 'Bibliothèque',
    subtitle: 'Neutral Systems',
    era: '2000–present',
    palette: ['#fafafa', '#f0f0f0', '#d8d8d8', '#5a5a5a', '#0a0a0a'],
    accent: '#5a5a5a',
    stance: 'The most precise thing in the room communicates the most authority. Neutrality as a maximum statement, detail as the only rhetoric.',
    tags: ['neutral', 'systematic', 'micro-craft', 'precision'],
  },
  {
    id: 'base-conceptual',
    skillId: 'hs-base-conceptual',
    directionId: 'editorial-monocle',
    name: 'Base Design',
    subtitle: 'Conceptual Editorial',
    era: '1993–present',
    palette: ['#f8f4ef', '#e8e0d5', '#b8a898', '#4a3c30', '#1a1510'],
    accent: '#4a3c30',
    stance: 'The concept is the design. Typography and whitespace in service of an idea — not a visual, an argument. Intelligence is the aesthetic.',
    tags: ['conceptual', 'editorial', 'whitespace', 'arts clients'],
  },
  {
    id: 'build-restrained',
    skillId: 'hs-build-restrained',
    directionId: 'luxury-build',
    name: 'Build',
    subtitle: 'Grid-Based Restraint',
    era: '2001–present',
    palette: ['#f5f5f5', '#e2e2e2', '#b0b0b0', '#4a4a4a', '#111111'],
    accent: '#4a4a4a',
    stance: 'Design as architecture — structural, loadbearing, exposed. Every decision is deliberate, documented, and defensible. The grid is the argument.',
    tags: ['grid', 'restrained', 'typographic minimalism', 'documented'],
  },
  {
    id: 'feixen-playful',
    skillId: 'hs-feixen-playful',
    directionId: 'warm-soft',
    name: 'Studio Feixen',
    subtitle: 'Flat Playful',
    era: '2009–present',
    palette: ['#ff6b6b', '#ffd93d', '#4ecdc4', '#45b7d1', '#f8f8f8'],
    accent: '#ff6b6b',
    stance: 'Swiss precision wearing a party hat. Joy is a formal property — achievable through geometric rigor, not in spite of it.',
    tags: ['flat', 'illustrative', 'playful', 'geometric characters'],
  },
  {
    id: 'snask-bold',
    skillId: 'hs-snask-bold',
    directionId: 'gamified-resn',
    name: 'Snask',
    subtitle: 'Bold Color / Cheeky',
    era: '2008–present',
    palette: ['#ff4757', '#ffa502', '#2ed573', '#1e90ff', '#fffefe'],
    accent: '#ff4757',
    stance: 'Brands are allowed to have personality. Primary colors pushed to extremes, vintage craft techniques, zero apology for being noticed.',
    tags: ['bold', 'primary palettes', 'vintage', 'personality'],
  },
  {
    id: 'spin-identity-arch',
    skillId: 'hs-spin-identity-arch',
    directionId: 'content-first-ia',
    name: 'Spin',
    subtitle: 'Identity Architecture',
    era: '1992–present',
    palette: ['#fafafa', '#e8e8e8', '#c0c0c0', '#1a1a1a', '#0055cc'],
    accent: '#0055cc',
    stance: 'Identity as infrastructure — modular, scalable, coherent at every size. The system should flex without losing recognition.',
    tags: ['systematic', 'modular', 'identity infrastructure', 'detail'],
  },
  {
    id: '2x4-information',
    skillId: 'hs-2x4-information',
    directionId: 'content-first-ia',
    name: '2x4',
    subtitle: 'Information Design',
    era: '1994–present',
    palette: ['#f0ece6', '#d4cdc4', '#7a7470', '#2c2c2c', '#0a0a0a'],
    accent: '#2c2c2c',
    stance: 'The image carries the argument. Editorial precision at the intersection of fashion, culture, and archives — minimal text, maximum reading.',
    tags: ['photo-led', 'editorial', 'fashion', 'information design'],
  },
  {
    id: 'why-not-expressive',
    skillId: 'hs-why-not-expressive',
    directionId: 'brutalist-experimental',
    name: 'Why Not Associates',
    subtitle: 'Expressive Typography',
    era: '1987–present',
    palette: ['#ff2d55', '#5856d6', '#ff9500', '#000000', '#f5f5f5'],
    accent: '#ff2d55',
    stance: 'Letterforms as image. Typography collaged, stretched, inverted — a post-punk energy where the type IS the illustration.',
    tags: ['expressive', 'collage', 'music culture', 'post-punk'],
  },
];
