/**
 * SlidesRenderer.tsx
 * 
 * Renders A2R Deck artifacts.
 * Uses AllternitDeckPlayer (Reveal.js wrapper) for presentations.
 */

import React, { useMemo } from 'react';
import { motion } from 'framer-motion';
import { AllternitDeckPlayer } from '@/components/a2r';
import type { ArtifactUIPart } from '@/lib/ai/ui-parts.types';

interface SlidesRendererProps {
  artifact: ArtifactUIPart;
  sessionId?: string;
  onMoATaskUpdate?: (tasks: any[]) => void;
}

/**
 * SlidesRenderer - A2R Deck Artifact Renderer
 * 
 * Wraps AllternitDeckPlayer for use in the Canvas/sidecar.
 * Provides full presentation capabilities.
 */
export function SlidesRenderer({
  artifact,
  sessionId,
  onMoATaskUpdate,
}: SlidesRendererProps) {
  // Parse slides from artifact content
  const slides = useMemo(() => {
    if (!artifact.content) {
      return [
        {
          id: 'slide-1',
          type: 'title' as const,
          title: artifact.title || 'Untitled Presentation',
          subtitle: 'Generated by A2R Deck',
        },
        {
          id: 'slide-2',
          type: 'content' as const,
          title: 'Overview',
          content: ['Point 1', 'Point 2', 'Point 3'],
        },
      ];
    }

    // Parse from markdown-like format
    const slideBlocks = artifact.content.split('---');
    return slideBlocks.map((block, index) => {
      const lines = block.trim().split('\n').filter(l => l.trim());
      const title = lines[0]?.replace(/^#+\s*/, '') || `Slide ${index + 1}`;
      const content = lines.slice(1).filter(l => l.trim() && !l.startsWith('#'));
      
      // Detect slide type
      let type: Slide['type'] = 'content';
      if (index === 0) type = 'title';
      else if (content.length === 0) type = 'title';
      else if (content[0]?.startsWith('>')) type = 'quote';
      else if (block.includes('```')) type = 'code';
      
      return {
        id: `slide-${index}`,
        type,
        title,
        content: content.map(l => l.replace(/^>\s*/, '').trim()),
      };
    });
  }, [artifact.content, artifact.title]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="h-full"
    >
      <AllternitDeckPlayer
        slides={slides}
        title={artifact.title}
        showToolbar={true}
        enablePresenterMode={true}
        className="h-full"
      />
    </motion.div>
  );
}

type Slide = {
  id: string;
  type: 'title' | 'content' | 'split' | 'image' | 'quote' | 'code';
  title: string;
  content?: string[];
  subtitle?: string;
};

export default SlidesRenderer;
