/**
 * SlidesRenderer.tsx
 * 
 * Renders presentation slide decks.
 * PowerPoint-style carousel with slide navigation.
 */

import React, { useState, useMemo, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  ChevronLeft, 
  ChevronRight, 
  Grid3x3, 
  Play,
  Download,
  Share2,
  Plus,
  MoreHorizontal,
  MonitorPlay
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { ArtifactUIPart } from '@/lib/ai/rust-stream-adapter';
import { cn } from '@/lib/utils';

interface SlidesRendererProps {
  artifact: ArtifactUIPart;
  sessionId?: string;
  onMoATaskUpdate?: (tasks: any[]) => void;
}

interface Slide {
  id: string;
  title: string;
  content: string[];
  notes?: string;
  layout: 'title' | 'content' | 'split' | 'image' | 'quote';
  imageUrl?: string;
}

export function SlidesRenderer({
  artifact,
  sessionId,
  onMoATaskUpdate,
}: SlidesRendererProps) {
  const [currentSlideIndex, setCurrentSlideIndex] = useState(0);
  const [showGrid, setShowGrid] = useState(false);
  const [presentMode, setPresentMode] = useState(false);

  // Parse slides from content (mock for now)
  const slides = useMemo<Slide[]>(() => {
    if (!artifact.content) {
      // Default slides for demo
      return [
        {
          id: 'slide-1',
          title: 'Welcome to the Presentation',
          content: ['Generated by A2rchitech', 'Powered by AI'],
          layout: 'title',
        },
        {
          id: 'slide-2',
          title: 'Agenda',
          content: [
            'Introduction',
            'Key Features',
            'Use Cases',
            'Q&A',
          ],
          layout: 'content',
        },
        {
          id: 'slide-3',
          title: 'Key Features',
          content: [
            'AI-powered generation',
            'Real-time collaboration',
            'Smart formatting',
          ],
          layout: 'split',
          imageUrl: '/placeholder-slide.png',
        },
      ];
    }

    // Parse from markdown-like format
    const slideBlocks = artifact.content.split('---');
    return slideBlocks.map((block, index) => {
      const lines = block.trim().split('\n');
      const title = lines[0] || `Slide ${index + 1}`;
      const content = lines.slice(1).filter(l => l.trim());
      
      return {
        id: `slide-${index}`,
        title,
        content,
        layout: index === 0 ? 'title' : 'content',
      };
    });
  }, [artifact.content]);

  // Navigation handlers
  const goToPreviousSlide = useCallback(() => {
    setCurrentSlideIndex(prev => Math.max(0, prev - 1));
  }, []);

  const goToNextSlide = useCallback(() => {
    setCurrentSlideIndex(prev => Math.min(slides.length - 1, prev + 1));
  }, [slides.length]);

  const goToSlide = useCallback((index: number) => {
    setCurrentSlideIndex(index);
  }, []);

  // Keyboard navigation
  React.useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (presentMode || showGrid) return;
      
      if (e.key === 'ArrowLeft') {
        goToPreviousSlide();
      } else if (e.key === 'ArrowRight') {
        goToNextSlide();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [presentMode, showGrid, goToPreviousSlide, goToNextSlide]);

  // Render slide based on layout
  const renderSlide = (slide: Slide, index: number) => {
    const isCurrent = index === currentSlideIndex;

    const slideContent = () => {
      switch (slide.layout) {
        case 'title':
          return (
            <div className="h-full flex flex-col items-center justify-center text-center p-12">
              <h1 className="text-5xl font-bold text-[var(--text-primary)] mb-4">
                {slide.title}
              </h1>
              {slide.content.map((line, i) => (
                <p key={i} className="text-xl text-[var(--text-secondary)] mt-2">
                  {line}
                </p>
              ))}
            </div>
          );

        case 'quote':
          return (
            <div className="h-full flex flex-col items-center justify-center p-12">
              <div className="text-3xl text-[var(--accent-primary)] mb-6">"</div>
              {slide.content.map((line, i) => (
                <p key={i} className="text-2xl text-[var(--text-primary)] italic text-center mb-4">
                  {line}
                </p>
              ))}
              <div className="text-lg text-[var(--text-tertiary)] mt-8">
                — {slide.title}
              </div>
            </div>
          );

        case 'split':
          return (
            <div className="h-full grid grid-cols-2 gap-8 p-8">
              <div className="flex flex-col justify-center">
                <h2 className="text-3xl font-bold text-[var(--text-primary)] mb-6">
                  {slide.title}
                </h2>
                <ul className="space-y-3">
                  {slide.content.map((item, i) => (
                    <li key={i} className="text-[var(--text-secondary)] flex items-start gap-2">
                      <span className="w-2 h-2 rounded-full bg-[var(--accent-primary)] mt-2 flex-shrink-0" />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div className="flex items-center justify-center bg-[var(--bg-primary)] rounded-lg">
                {slide.imageUrl ? (
                  <img src={slide.imageUrl} alt="" className="max-w-full max-h-full object-contain" />
                ) : (
                  <div className="text-[var(--text-tertiary)] text-sm">Image placeholder</div>
                )}
              </div>
            </div>
          );

        case 'content':
        default:
          return (
            <div className="h-full flex flex-col p-8">
              <h2 className="text-3xl font-bold text-[var(--text-primary)] mb-8">
                {slide.title}
              </h2>
              <div className="flex-1">
                <ul className="space-y-4">
                  {slide.content.map((item, i) => (
                    <li key={i} className="text-[var(--text-secondary)] text-lg flex items-start gap-3">
                      <span className="w-2 h-2 rounded-full bg-[var(--accent-primary)] mt-2.5 flex-shrink-0" />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          );
      }
    };

    return (
      <div
        className={cn(
          "w-full h-full bg-[var(--bg-primary)] rounded-lg border border-[var(--border-subtle)]",
          isCurrent ? 'opacity-100' : 'opacity-0 absolute inset-0'
        )}
      >
        {slideContent()}
      </div>
    );
  };

  // Present mode overlay
  if (presentMode) {
    return (
      <div className="fixed inset-0 z-50 bg-black flex items-center justify-center">
        <div className="w-full h-full max-w-7xl max-h-[90vh] aspect-video">
          {renderSlide(slides[currentSlideIndex], currentSlideIndex)}
        </div>

        {/* Present mode controls */}
        <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex items-center gap-4 px-6 py-3 rounded-full bg-black/80 backdrop-blur">
          <Button
            variant="ghost"
            size="sm"
            onClick={goToPreviousSlide}
            disabled={currentSlideIndex === 0}
            className="text-white hover:bg-white/20"
          >
            <ChevronLeft className="w-5 h-5" />
          </Button>
          <span className="text-white text-sm font-medium">
            {currentSlideIndex + 1} / {slides.length}
          </span>
          <Button
            variant="ghost"
            size="sm"
            onClick={goToNextSlide}
            disabled={currentSlideIndex === slides.length - 1}
            className="text-white hover:bg-white/20"
          >
            <ChevronRight className="w-5 h-5" />
          </Button>
          <div className="w-px h-4 bg-white/30" />
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setPresentMode(false)}
            className="text-white hover:bg-white/20"
          >
            Exit
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col bg-[var(--bg-secondary)]">
      {/* Toolbar */}
      <div className="h-12 border-b border-[var(--border-subtle)] flex items-center justify-between px-4">
        <div className="flex items-center gap-3">
          <span className="text-sm font-medium text-[var(--text-primary)]">
            {artifact.title}
          </span>
          <span className="text-xs text-[var(--text-tertiary)]">
            {slides.length} slides
          </span>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setShowGrid(!showGrid)}
            className="text-[var(--text-tertiary)] hover:text-[var(--text-primary)]"
          >
            <Grid3x3 className="w-4 h-4" />
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setPresentMode(true)}
            className="text-[var(--text-tertiary)] hover:text-[var(--text-primary)]"
          >
            <Play className="w-4 h-4" />
          </Button>
          <Button variant="ghost" size="sm" className="text-[var(--text-tertiary)]">
            <Download className="w-4 h-4" />
          </Button>
          <Button variant="ghost" size="sm" className="text-[var(--text-tertiary)]">
            <Share2 className="w-4 h-4" />
          </Button>
          <Button variant="ghost" size="sm" className="text-[var(--text-tertiary)]">
            <MoreHorizontal className="w-4 h-4" />
          </Button>
        </div>
      </div>

      {/* Main content */}
      <div className="flex-1 flex items-center justify-center p-8 overflow-hidden">
        <AnimatePresence mode="wait">
          <motion.div
            key={currentSlideIndex}
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -50 }}
            transition={{ duration: 0.3 }}
            className="w-full max-w-4xl aspect-video"
          >
            {renderSlide(slides[currentSlideIndex], currentSlideIndex)}
          </motion.div>
        </AnimatePresence>
      </div>

      {/* Navigation */}
      <div className="h-14 border-t border-[var(--border-subtle)] flex items-center justify-between px-4 bg-[var(--bg-primary)]">
        <Button
          variant="ghost"
          size="sm"
          onClick={goToPreviousSlide}
          disabled={currentSlideIndex === 0}
          className="text-[var(--text-tertiary)] hover:text-[var(--text-primary)] disabled:opacity-30"
        >
          <ChevronLeft className="w-4 h-4" />
          <span className="ml-2 text-xs">Previous</span>
        </Button>

        <div className="flex items-center gap-2">
          {slides.map((_, index) => (
            <button
              key={index}
              onClick={() => goToSlide(index)}
              className={cn(
                "w-2 h-2 rounded-full transition-colors",
                index === currentSlideIndex
                  ? "bg-[var(--accent-primary)]"
                  : "bg-[var(--border-subtle)] hover:bg-[var(--text-tertiary)]"
              )}
            />
          ))}
        </div>

        <div className="text-xs text-[var(--text-tertiary)]">
          {currentSlideIndex + 1} / {slides.length}
        </div>

        <Button
          variant="ghost"
          size="sm"
          onClick={goToNextSlide}
          disabled={currentSlideIndex === slides.length - 1}
          className="text-[var(--text-tertiary)] hover:text-[var(--text-primary)] disabled:opacity-30"
        >
          <span className="mr-2 text-xs">Next</span>
          <ChevronRight className="w-4 h-4" />
        </Button>
      </div>

      {/* Slide grid overlay */}
      <AnimatePresence>
        {showGrid && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 z-10 bg-black/80 backdrop-blur-sm p-8 overflow-auto"
            onClick={() => setShowGrid(false)}
          >
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 max-w-7xl mx-auto">
              {slides.map((slide, index) => (
                <motion.div
                  key={slide.id}
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: index * 0.05 }}
                  className={cn(
                    "aspect-video rounded-lg border-2 cursor-pointer transition-all",
                    index === currentSlideIndex
                      ? "border-[var(--accent-primary)] bg-[var(--bg-primary)]"
                      : "border-[var(--border-subtle)] bg-[var(--bg-secondary)] hover:border-[var(--text-tertiary)]"
                  )}
                  onClick={(e) => {
                    e.stopPropagation();
                    goToSlide(index);
                    setShowGrid(false);
                  }}
                >
                  <div className="p-3">
                    <div className="text-xs font-medium text-[var(--text-primary)] truncate">
                      {index + 1}. {slide.title}
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
