#!/usr/bin/env bash
set -euo pipefail

# Get the latest Git tag
latest_tag=$(git tag --sort=committerdate | grep -E '^vscode-v[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)
if [ -z "$latest_tag" ]; then
    echo "No tags found"
    exit 1
fi
echo "Latest tag: $latest_tag"
version=$(echo "$latest_tag" | sed 's/^vscode-v//')
echo "Latest version: $version"

# package-marketplace
vsce package --no-git-tag-version --no-update-package-json --no-dependencies --skip-license -o dist/gizzi-code.vsix "$version"

# publish-marketplace
vsce publish --packagePath dist/gizzi-code.vsix

# publish-openvsx
npx ovsx publish dist/gizzi-code.vsix -p "$OPENVSX_TOKEN"
