/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TsUiSpec {
  specId: string
  title: string
  description: string
  components: Array<TsComponentSpec>
  layout: TsLayoutSpec
  style: TsStyleSpec
  interactions: Array<TsInteractionSpec>
  createdAt: string
}
export interface TsComponentSpec {
  componentId: string
  componentType: string
  properties: any
  children: Array<string>
  bindings: Array<TsDataBinding>
}
export interface TsDataBinding {
  property: string
  source: string
  transform?: string
}
export interface TsLayoutSpec {
  layoutType: string
  constraints: TsLayoutConstraints
  regions: Array<TsLayoutRegionSpec>
}
export interface TsLayoutConstraints {
  minWidth?: number
  maxWidth?: number
  minHeight?: number
  maxHeight?: number
}
export interface TsLayoutRegionSpec {
  regionId: string
  regionType: string
  position: TsRegionPosition
  size: TsRegionSize
}
export interface TsRegionPosition {
  x: number
  y: number
}
export interface TsRegionSize {
  width: number
  height: number
}
export interface TsStyleSpec {
  theme: string
  colors: Record<string, string>
  typography: TsTypographySpec
  spacing: TsSpacingSpec
}
export interface TsTypographySpec {
  fontFamily: string
  fontSizes: Record<string, number>
  lineHeights: Record<string, number>
}
export interface TsSpacingSpec {
  scale: Array<number>
  unit: string
}
export interface TsInteractionSpec {
  interactionId: string
  trigger: string
  action: string
  target: string
}
export interface TsGeneratedUi {
  generationId: string
  specId: string
  uiCode: string
  uiType: string
  componentsGenerated: number
  confidence: number
  generationHash?: string
}
export interface TsSpecDiff {
  hasChanges: boolean
  componentChanges: Array<TsComponentChange>
  layoutChanges: Array<TsLayoutChange>
  styleChanges: Array<TsStyleChange>
  breakingChanges: Array<TsBreakingChange>
}
export interface TsComponentChange {
  changeType: string
  componentId: string
  description: string
}
export interface TsLayoutChange {
  field: string
  oldValue: string
  newValue: string
}
export interface TsStyleChange {
  category: string
  property: string
  oldValue: string
  newValue: string
}
export interface TsBreakingChange {
  severity: string
  description: string
  migrationGuide: string
}
export interface TsA11YResult {
  passed: boolean
  score: number
  violations: Array<TsA11yViolation>
  warnings: Array<TsA11yWarning>
}
export interface TsA11YViolation {
  rule: string
  severity: string
  description: string
  element: string
  remediation: string
  wcagReference: string
}
export interface TsA11YWarning {
  rule: string
  description: string
  element: string
  suggestion: string
}
export declare function version(): string
export declare class TamboEngineNapi {
  constructor()
  /** Initialize engine with default components (async) */
  static initWithDefaults(): Promise<TamboEngineNapi>
  /** Generate UI (standard mode) */
  generateUi(spec: TsUiSpec, uiType: string): Promise<TsGeneratedUi>
  /** Generate UI with validation */
  generateUiValidated(spec: TsUiSpec, uiType: string): Promise<TsGeneratedUi>
  /** Generate UI with reproducibility (seed-based) */
  generateUiReproducible(spec: TsUiSpec, uiType: string, seed: number): Promise<TsGeneratedUi>
  /** Save generation state */
  saveGenerationState(generationId: string, specId: string, state: string): Promise<void>
  /** Load generation state */
  loadGenerationState(generationId: string): Promise<string | null>
  /** Hash arbitrary content */
  hashContent(content: string): string
  /** Verify content against expected hash */
  verifyHash(content: string, expectedHash: string): boolean
  /** Compare two specs and return differences */
  diffSpecs(oldSpec: TsUiSpec, newSpec: TsUiSpec): TsSpecDiff
  /** Check if spec diff has breaking changes */
  hasBreakingChanges(diff: TsSpecDiff): boolean
  /** Generate human-readable summary of changes */
  summarizeChanges(diff: TsSpecDiff): string
  /** Validate spec for accessibility */
  validateA11Y(spec: TsUiSpec): TsA11yResult
  /** Validate generated UI for accessibility */
  validateUiA11Y(ui: TsGeneratedUi): TsA11yResult
  /** Generate accessibility report */
  generateA11YReport(result: TsA11yResult): string
}
