/**
 * Graph Builder
 *
 * Extracts entities and relationships from vault notes to build a
 * traversable knowledge graph, then materializes entity/sub-hub notes and
 * leaf-to-leaf/cross-cluster semantic edges. See
 * docs/LENS_CONTEXT_LAYER_PLAN.md and the graph-topology plan for why:
 * hub notes were accumulating hundreds of flat inbound edges
 * (hub-and-spoke), there was no semantic linking at all, and entity notes
 * were create-once-never-updated so a hub could never react to new
 * mentions. All deterministic — no LLM calls, no network, no randomness;
 * the same vault content always produces the same graph.
 */

import path from "path"
import { Log } from "@/shared/util/log"
import { Vault } from "../types"
import * as IO from "../io"
import { tokenize, computeDocumentFrequencies, embed } from "./embedding"
import { computeSemanticEdges, type SemanticEdge } from "./semantic-linking"
import { withAutoGeneratedSection } from "./markers"

const log = Log.create({ service: "vault-graph" })

const ENTITY_PATTERNS: Array<{ type: Vault.EntityType; regex: RegExp }> = [
  { type: "person", regex: /(?:^|\n)(?:##?#?\s*)?(?:From|To|Attendee|Owner|Assigned to):?\s*([^\n]+)/gi },
  { type: "project", regex: /(?:^|\n)(?:##?#?\s*)?(?:Project|Workstream|Epic):?\s*([^\n]+)/gi },
  { type: "decision", regex: /(?:^|\n)(?:##?#?\s*)?(?:Decision|Resolved|Agreed):?\s*([^\n]+)/gi },
  { type: "task", regex: /(?:^|\n)\s*[-*]\s+\[([ xX])\]\s*([^\n]+)/gi },
]

// Above this many related notes, an entity note demotes to sub-hubs instead
// of a flat list. "Hub notes should be ~10 links to sub-hubs, not 800 links
// to leaves."
const HUB_DEMOTION_THRESHOLD = 15
// Deterministic last-resort grouping when source/folder both fail to split
// an oversized group (e.g. an all-brain-authored hub sitting in one folder).
const HASH_BUCKET_FALLBACK_COUNT = 5

// Leaf-to-leaf semantic neighbors.
const SIMILAR_TOP_K = 5
const SIMILAR_THRESHOLD = 0.15
// Cross-cluster bridges: rarer, more selective than plain "similar" edges —
// "what in domain X relates to this domain Y note."
const BRIDGE_TOP_K = 2
const BRIDGE_THRESHOLD = 0.2

// Static marker (no timestamp) so regenerating an unchanged note produces
// byte-identical output — required for determinism. Any hand-written prose
// outside these markers is preserved across regenerations.
const AUTO_START = "<!-- gizzi-graph:auto-generated:start -->"
const AUTO_END = "<!-- gizzi-graph:auto-generated:end -->"

export interface ExtractedEntity {
  name: string
  type: Vault.EntityType
  context: string
  notePath: string
}

export function extractEntities(note: Vault.Note): ExtractedEntity[] {
  const entities: ExtractedEntity[] = []
  const seen = new Set<string>()

  for (const { type, regex } of ENTITY_PATTERNS) {
    let match: RegExpExecArray | null
    while ((match = regex.exec(note.content)) !== null) {
      const name = (match[2] || match[1]!).trim().substring(0, 200)
      if (!name || seen.has(`${type}:${name}`)) continue
      seen.add(`${type}:${name}`)
      entities.push({
        name,
        type,
        context: note.title,
        notePath: note.relPath,
      })
    }
    regex.lastIndex = 0
  }

  // Extract people from "From: Name <email>" patterns (email threads)
  const fromMatches = note.content.match(/From:\s*([^<\n]+)/g)
  if (fromMatches) {
    for (const m of fromMatches) {
      const name = m.replace("From:", "").trim().split("<")[0]!.trim()
      if (name && !seen.has(`person:${name}`)) {
        seen.add(`person:${name}`)
        entities.push({ name, type: "person", context: note.title, notePath: note.relPath })
      }
    }
  }

  return entities
}

export function buildGraph(notes: Vault.Note[]): Vault.Graph {
  const nodes = new Map<string, Vault.GraphNode>()
  const edges: Vault.GraphEdge[] = []

  for (const note of notes) {
    const nodeId = note.relPath

    if (!nodes.has(nodeId)) {
      nodes.set(nodeId, {
        id: nodeId,
        title: note.title,
        type: Vault.inferEntityType(note),
        path: note.relPath,
        edges: [],
      })
    }

    const node = nodes.get(nodeId)!

    // Outgoing wikilinks
    for (const link of note.outgoingLinks) {
      const targetId = link.endsWith(".md") ? link : `${link}.md`
      const edge: Vault.GraphEdge = {
        target: targetId,
        relation: "related",
      }
      node.edges.push(edge)
      edges.push(edge)
    }

    // Extracted entities become their own nodes
    const entities = extractEntities(note)
    for (const entity of entities) {
      const entityId = `entity/${entity.type}/${IO.sanitizeFilename(entity.name)}.md`
      if (!nodes.has(entityId)) {
        nodes.set(entityId, {
          id: entityId,
          title: entity.name,
          type: entity.type,
          path: entityId,
          edges: [],
        })
      }
      const entNode = nodes.get(entityId)!
      const edge: Vault.GraphEdge = {
        target: nodeId,
        relation: entity.type === "person" ? "attended" : entity.type === "decision" ? "decided_in" : "related",
        context: entity.context,
      }
      entNode.edges.push(edge)
      edges.push(edge)
    }
  }

  return { nodes, edges }
}

/**
 * buildGraph() plus leaf-to-leaf semantic edges and cross-cluster bridges.
 * Kept separate from buildGraph() itself so that function stays a pure,
 * simple wikilink+entity assembly (unchanged behavior for anything that
 * only needs that). Returns the semantic edges separately too, so the
 * caller can persist them (VaultManager.replaceSemanticLinks) without this
 * module needing a SQLite/VaultIndex dependency.
 */
export function buildGraphWithSemanticLinking(notes: Vault.Note[]): { graph: Vault.Graph; semanticEdges: SemanticEdge[] } {
  const graph = buildGraph(notes)

  const tokenized = notes.map((n) => tokenize(n.content))
  const df = computeDocumentFrequencies(tokenized)
  const embeddings = new Map<string, number[]>()
  notes.forEach((n, i) => embeddings.set(n.relPath, embed(tokenized[i]!, df, notes.length)))

  const similar = computeSemanticEdges(notes, embeddings, {
    relation: "similar",
    topK: SIMILAR_TOP_K,
    threshold: SIMILAR_THRESHOLD,
  })
  const bridges = computeSemanticEdges(notes, embeddings, {
    relation: "bridge",
    topK: BRIDGE_TOP_K,
    threshold: BRIDGE_THRESHOLD,
    crossClusterOnly: true,
  })
  const semanticEdges = [...similar, ...bridges]

  // Merge into the in-memory graph (both directions — similarity is
  // symmetric, unlike wikilinks/entity-mention edges above).
  for (const se of semanticEdges) {
    const sourceNode = graph.nodes.get(se.source)
    const targetNode = graph.nodes.get(se.target)
    if (sourceNode) {
      const edge: Vault.GraphEdge = { target: se.target, relation: se.relation, weight: se.weight }
      sourceNode.edges.push(edge)
      graph.edges.push(edge)
    }
    if (targetNode) {
      const edge: Vault.GraphEdge = { target: se.source, relation: se.relation, weight: se.weight }
      targetNode.edges.push(edge)
      graph.edges.push(edge)
    }
  }

  return { graph, semanticEdges }
}

async function writeGraphNote(
  vaultRoot: string,
  relId: string,
  title: string,
  type: Vault.EntityType,
  bodyLines: string[],
): Promise<void> {
  const absPath = path.join(vaultRoot, relId)
  const existing = await IO.readNote(absPath, vaultRoot)
  const content = withAutoGeneratedSection(existing?.content ?? `## ${title}\n`, bodyLines, { start: AUTO_START, end: AUTO_END })
  const frontmatter: Vault.Frontmatter = {
    title,
    type,
    tags: existing?.frontmatter.tags?.length ? existing.frontmatter.tags : [type],
  }
  await IO.writeNote(absPath, { frontmatter, content })
}

function groupKeyFor(note: Vault.Note): string {
  if (note.frontmatter.source) return note.frontmatter.source
  return note.folder.split("/")[0] || "root"
}

function hashBucket(relPath: string, buckets: number): number {
  let hash = 0
  for (let i = 0; i < relPath.length; i++) {
    hash = ((hash << 5) - hash + relPath.charCodeAt(i)) | 0
  }
  return Math.abs(hash) % buckets
}

/**
 * Group an oversized related-notes set for hub demotion: by source, falling
 * back to top-level folder, falling back (when that still yields one
 * oversized group — e.g. an all-brain-authored hub in one folder) to a
 * deterministic hash bucket of relPath. Capped at one level of demotion:
 * if a resulting group is itself still huge, that's a documented
 * limitation, not recursively handled.
 */
function groupRelatedNotes(relatedNotes: Vault.Note[]): Map<string, Vault.Note[]> | null {
  if (relatedNotes.length <= HUB_DEMOTION_THRESHOLD) return null

  let groups = new Map<string, Vault.Note[]>()
  for (const n of relatedNotes) {
    const key = groupKeyFor(n)
    if (!groups.has(key)) groups.set(key, [])
    groups.get(key)!.push(n)
  }

  if (groups.size === 1) {
    groups = new Map()
    for (const n of relatedNotes) {
      const key = `bucket-${hashBucket(n.relPath, HASH_BUCKET_FALLBACK_COUNT)}`
      if (!groups.has(key)) groups.set(key, [])
      groups.get(key)!.push(n)
    }
  }

  return groups
}

export async function ensureEntityNotes(vaultRoot: string, notes: Vault.Note[], graph?: Vault.Graph): Promise<void> {
  const g = graph ?? buildGraph(notes)
  const notesByPath = new Map(notes.map((n) => [n.relPath, n]))

  for (const [id, node] of g.nodes) {
    if (!id.startsWith("entity/")) continue

    const relatedNotes = node.edges
      .map((e) => notesByPath.get(e.target))
      .filter((n): n is Vault.Note => n !== undefined)

    const groups = groupRelatedNotes(relatedNotes)

    if (!groups) {
      // Small enough — flat list, no demotion needed.
      await writeGraphNote(vaultRoot, id, node.title, node.type, [
        "### Related Notes",
        "",
        ...relatedNotes.map((n) => `- [[${n.title}]]`),
      ])
      continue
    }

    // Demotion: one sub-hub note per group; the parent entity note links
    // only to the (typically far fewer than 10) sub-hubs, not the leaves.
    const entityDir = id.slice(0, -".md".length)
    const subHubRefs: Array<{ title: string; id: string }> = []
    for (const [groupKey, groupNotes] of groups) {
      const sanitizedKey = IO.sanitizeFilename(groupKey)
      const subHubId = path.join(entityDir, `${sanitizedKey}.md`)
      const subHubTitle = `${node.title} — ${groupKey}`
      await writeGraphNote(vaultRoot, subHubId, subHubTitle, node.type, [
        "### Related Notes",
        "",
        ...groupNotes.map((n) => `- [[${n.title}]]`),
      ])
      subHubRefs.push({ title: subHubTitle, id: subHubId })
    }

    await writeGraphNote(vaultRoot, id, node.title, node.type, [
      `### Sub-hubs (${subHubRefs.length})`,
      "",
      ...subHubRefs.map((r) => `- [[${r.title}]]`),
    ])
  }

  log.info("Entity notes ensured", { count: [...g.nodes.keys()].filter((id) => id.startsWith("entity/")).length })
}
