/**
 * Shared idempotent-regeneration algorithm for auto-generated note
 * sections: strip any existing marked section, append a fresh one,
 * leaving hand-written prose outside the markers untouched. Extracted
 * from vault/graph/build.ts so codemap/vault-export.ts can reuse the same
 * algorithm without duplicating it — but each caller supplies its own
 * marker strings, so a note's source is never ambiguous and the two
 * systems stay decoupled (see build.ts's AUTO_START/AUTO_END vs
 * vault-export.ts's own gizzi-codemap:... markers).
 */

export interface AutoGeneratedMarkers {
  start: string
  end: string
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

/** Replace the auto-generated section in place, leaving any hand-written prose untouched. */
export function withAutoGeneratedSection(existingContent: string, lines: string[], markers: AutoGeneratedMarkers): string {
  const marker = new RegExp(`${escapeRegExp(markers.start)}[\\s\\S]*?${escapeRegExp(markers.end)}\\n?`, "g")
  const stripped = existingContent.replace(marker, "").trimEnd()
  const section = [markers.start, ...lines, markers.end].join("\n")
  return stripped.length > 0 ? `${stripped}\n\n${section}\n` : `${section}\n`
}
