import type { DesignPluginDefinition } from './designPlugin.types';
import { DESIGN_SKILLS_REGISTRY } from './designSkills.registry';

function skillsFor(bucket: DesignPluginDefinition['id']) {
  return DESIGN_SKILLS_REGISTRY.filter((skill) => skill.bucket === bucket).map((skill) => skill.id);
}

export const DESIGN_PLUGINS_REGISTRY: DesignPluginDefinition[] = [
  {
    id: 'frontend',
    name: 'Frontend',
    description:
      'Design, audit, refine, and export interface work across layout, interaction, accessibility, and implementation polish.',
    summary: 'Make the interface better and build it.',
    capabilities: [
      'UI generation',
      'layout refinement',
      'accessibility audits',
      'component specification',
      'responsive adaptation',
      'frontend polish',
    ],
    supportedSurfaces: ['design', 'canvas', 'allternit-canvas', 'code-skills', 'marketplace', 'selection'],
    inputs: ['prompt', 'brief', 'screenshot', 'component', 'code', 'URL'],
    outputs: ['UI direction', 'audit report', 'component spec', 'refined screen', 'frontend handoff'],
    bundledSkillIds: skillsFor('frontend'),
    actions: [
      {
        id: 'frontend-generate-ui',
        label: 'Generate UI',
        description: 'Create or restyle interface work with strong hierarchy and implementation-aware structure.',
        inputModes: ['prompt', 'brief', 'reference'],
        outputModes: ['screen-direction', 'component-plan'],
        supportedSurfaces: ['design', 'canvas', 'marketplace'],
      },
      {
        id: 'frontend-audit-screen',
        label: 'Audit Current Screen',
        description: 'Review the current UI for accessibility, quality, spacing, and interface anti-patterns.',
        inputModes: ['screen', 'selection', 'URL'],
        outputModes: ['audit-report', 'fix-list'],
        supportedSurfaces: ['design', 'selection', 'marketplace'],
      },
      {
        id: 'frontend-refine-layout',
        label: 'Refine Layout',
        description: 'Improve spacing, rhythm, hierarchy, and responsive structure.',
        inputModes: ['screen', 'component'],
        outputModes: ['layout-pass'],
        supportedSurfaces: ['design', 'canvas', 'selection'],
      },
      {
        id: 'frontend-improve-accessibility',
        label: 'Improve Accessibility',
        description: 'Repair common accessibility problems in interface structure, contrast, and semantics.',
        inputModes: ['code', 'screen', 'URL'],
        outputModes: ['accessibility-report', 'remediation-pass'],
        supportedSurfaces: ['design', 'code-skills', 'selection'],
      },
      {
        id: 'frontend-component-spec',
        label: 'Create Component Spec',
        description: 'Translate a UI direction into reusable components and implementation guidance.',
        inputModes: ['screen', 'component', 'brief'],
        outputModes: ['component-spec', 'implementation-guidance'],
        supportedSurfaces: ['design', 'code-skills', 'marketplace'],
      },
      {
        id: 'frontend-export-direction',
        label: 'Convert Direction to Frontend',
        description: 'Carry a chosen visual direction into implementation-ready frontend output.',
        inputModes: ['design-direction', 'screen', 'code'],
        outputModes: ['frontend-handoff', 'implementation-plan'],
        supportedSurfaces: ['design', 'code-skills'],
      },
    ],
  },
  {
    id: 'brand',
    name: 'Brand',
    description:
      'Create and manage identity systems, visual direction, image-based assets, and branded presentation materials.',
    summary: 'Make the visuals and brand materials.',
    capabilities: [
      'brand direction',
      'logo concepts',
      'asset packs',
      'campaign visuals',
      'visual identity systems',
      'presentation visuals',
    ],
    supportedSurfaces: ['design', 'canvas', 'allternit-canvas', 'marketplace', 'selection'],
    inputs: ['brief', 'prompt', 'references', 'existing assets', 'screenshots'],
    outputs: ['brand direction', 'logo set', 'asset pack', 'campaign graphics', 'visual system'],
    bundledSkillIds: skillsFor('brand'),
    actions: [
      {
        id: 'brand-generate-direction',
        label: 'Generate Brand Direction',
        description: 'Develop the visual language, themes, and graphic attitude of a brand or campaign.',
        inputModes: ['brief', 'references', 'prompt'],
        outputModes: ['brand-direction', 'visual-philosophy'],
        supportedSurfaces: ['design', 'canvas', 'marketplace'],
      },
      {
        id: 'brand-logo-concepts',
        label: 'Create Logo Concepts',
        description: 'Produce identity marks or logo directions with a defined visual stance.',
        inputModes: ['brief', 'references'],
        outputModes: ['logo-concepts'],
        supportedSurfaces: ['design', 'canvas'],
      },
      {
        id: 'brand-asset-pack',
        label: 'Produce Asset Pack',
        description: 'Generate coherent marketing, product, or campaign visual assets.',
        inputModes: ['brief', 'references', 'screenshots'],
        outputModes: ['asset-pack'],
        supportedSurfaces: ['canvas', 'allternit-canvas', 'design'],
      },
      {
        id: 'brand-campaign-visuals',
        label: 'Create Campaign Visuals',
        description: 'Build presentation, launch, or social visuals consistent with the selected brand system.',
        inputModes: ['brief', 'content', 'references'],
        outputModes: ['campaign-visuals'],
        supportedSurfaces: ['canvas', 'design'],
      },
      {
        id: 'brand-apply-system',
        label: 'Apply Style System',
        description: 'Apply a chosen identity system across assets and visual surfaces.',
        inputModes: ['existing-assets', 'style-system'],
        outputModes: ['styled-assets'],
        supportedSurfaces: ['canvas', 'design', 'selection'],
      },
      {
        id: 'brand-expand-identity',
        label: 'Expand Identity',
        description: 'Extend a brand into a larger kit of visual rules, assets, and expressive variants.',
        inputModes: ['brand-direction', 'existing-assets'],
        outputModes: ['identity-extension'],
        supportedSurfaces: ['design', 'canvas'],
      },
    ],
  },
  {
    id: 'motion',
    name: 'Motion',
    description:
      'Design and tune transitions, microinteractions, motion systems, and media-forward presentation behavior.',
    summary: 'Make it move and present well.',
    capabilities: [
      'motion passes',
      'transition systems',
      'microinteractions',
      'performance tuning',
      'animated demos',
      'interaction choreography',
    ],
    supportedSurfaces: ['design', 'canvas', 'allternit-canvas', 'marketplace', 'selection', 'code-skills'],
    inputs: ['screen', 'flow', 'component', 'code', 'prompt'],
    outputs: ['motion spec', 'transition plan', 'animation pass', 'performance fixes', 'demo sequence'],
    bundledSkillIds: skillsFor('motion'),
    actions: [
      {
        id: 'motion-add-pass',
        label: 'Add Motion Pass',
        description: 'Layer motion and feedback onto an existing interface or flow.',
        inputModes: ['screen', 'flow', 'component'],
        outputModes: ['motion-pass'],
        supportedSurfaces: ['design', 'canvas', 'selection'],
      },
      {
        id: 'motion-transition-system',
        label: 'Design Transition System',
        description: 'Create consistent enter, exit, modal, and surface transition behavior.',
        inputModes: ['screen', 'component'],
        outputModes: ['transition-system'],
        supportedSurfaces: ['design', 'canvas'],
      },
      {
        id: 'motion-microinteractions',
        label: 'Create Microinteractions',
        description: 'Add focused hover, press, toggle, and response patterns that improve feel.',
        inputModes: ['component', 'screen'],
        outputModes: ['microinteraction-spec'],
        supportedSurfaces: ['design', 'canvas', 'selection'],
      },
      {
        id: 'motion-performance',
        label: 'Improve Motion Performance',
        description: 'Tune animation implementations to avoid jank and expensive rendering paths.',
        inputModes: ['code', 'animation'],
        outputModes: ['performance-fixes'],
        supportedSurfaces: ['design', 'code-skills'],
      },
      {
        id: 'motion-animate-screen',
        label: 'Animate Existing Screen',
        description: 'Apply a clear animation layer to an already-designed UI.',
        inputModes: ['screen', 'selection'],
        outputModes: ['animated-screen-plan'],
        supportedSurfaces: ['design', 'canvas', 'selection'],
      },
      {
        id: 'motion-demo-sequence',
        label: 'Generate Demo Sequence',
        description: 'Turn a UI or visual concept into a more cinematic walkthrough or presentation sequence.',
        inputModes: ['screen', 'brief', 'content'],
        outputModes: ['demo-sequence'],
        supportedSurfaces: ['canvas', 'design'],
      },
    ],
  },
];
