import type { ImportedDesignSkill } from './designPlugin.types';

export const DESIGN_SKILLS_REGISTRY: ImportedDesignSkill[] = [
  {
    id: 'frontend-design',
    name: 'Frontend Design',
    source: 'anthropics/skills',
    description: 'Production-grade frontend interface design with strong craft and implementation-aware output.',
    bucket: 'frontend',
    priority: 'core',
    tags: ['ui', 'frontend', 'craft'],
    capabilities: ['ui-generation', 'implementation-handoff', 'visual-direction'],
    inputTypes: ['prompt', 'reference', 'screenshot'],
    outputTypes: ['ui-direction', 'frontend-spec', 'component-plan'],
    supportedSurfaces: ['design', 'canvas', 'code-skills', 'marketplace'],
  },
  {
    id: 'baseline-ui',
    name: 'Baseline UI',
    source: 'ibelick/ui-skills',
    description: 'Consistency, typography, accessibility, and motion guardrails for shipped interfaces.',
    bucket: 'frontend',
    priority: 'core',
    tags: ['validation', 'accessibility', 'ui-systems'],
    capabilities: ['consistency-audit', 'accessibility-check', 'layout-guardrails'],
    inputTypes: ['code', 'component', 'screen'],
    outputTypes: ['audit', 'fix-list'],
    supportedSurfaces: ['design', 'code-skills', 'selection'],
  },
  {
    id: 'fixing-accessibility',
    name: 'Fixing Accessibility',
    source: 'ibelick/ui-skills',
    description: 'Repair semantic, keyboard, contrast, and ARIA issues in interface work.',
    bucket: 'frontend',
    priority: 'core',
    tags: ['accessibility', 'wcag', 'html'],
    capabilities: ['accessibility-remediation', 'semantic-fixes'],
    inputTypes: ['code', 'screen', 'URL'],
    outputTypes: ['accessibility-report', 'remediation-pass'],
    supportedSurfaces: ['design', 'code-skills', 'selection'],
  },
  {
    id: 'fixing-metadata',
    name: 'Fixing Metadata',
    source: 'ibelick/ui-skills',
    description: 'Fix metadata, sharing previews, and structured page-level presentation details.',
    bucket: 'frontend',
    priority: 'supporting',
    tags: ['metadata', 'seo', 'presentation'],
    capabilities: ['metadata-audit', 'preview-fixes'],
    inputTypes: ['code', 'page'],
    outputTypes: ['metadata-report', 'fix-list'],
    supportedSurfaces: ['design', 'code-skills'],
  },
  {
    id: 'ui-ux-pro-max',
    name: 'UI UX Pro Max',
    source: 'nextlevelbuilder/ui-ux-pro-max-skill',
    description: 'Wide UI/UX decision system spanning layouts, palettes, typography, and design heuristics.',
    bucket: 'frontend',
    priority: 'core',
    tags: ['ui', 'ux', 'systems'],
    capabilities: ['design-reasoning', 'layout-systems', 'quality-control'],
    inputTypes: ['prompt', 'brief', 'screen'],
    outputTypes: ['design-direction', 'heuristics'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'design',
    name: 'Design',
    source: 'nextlevelbuilder/ui-ux-pro-max-skill',
    description: 'High-level design guidance for interface structure, tone, and visual decision making.',
    bucket: 'frontend',
    priority: 'supporting',
    tags: ['design', 'direction', 'structure'],
    capabilities: ['structure', 'visual-direction'],
    inputTypes: ['prompt', 'brief'],
    outputTypes: ['design-brief', 'direction'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'impeccable',
    name: 'Impeccable',
    source: 'pbakaus/impeccable',
    description: 'Anti-generic premium frontend craft with strong rules for hierarchy, color, type, and polish.',
    bucket: 'frontend',
    priority: 'core',
    tags: ['craft', 'polish', 'anti-generic'],
    capabilities: ['premium-polish', 'visual-refinement', 'design-laws'],
    inputTypes: ['screen', 'component', 'prompt'],
    outputTypes: ['quality-pass', 'refined-ui'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'canvas-design',
    name: 'Canvas Design',
    source: 'anthropics/skills',
    description: 'Create original visual compositions and art-directed design assets on digital canvases.',
    bucket: 'brand',
    priority: 'core',
    tags: ['canvas', 'visuals', 'art-direction'],
    capabilities: ['visual-generation', 'art-direction'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['canvas-composition', 'asset-direction'],
    supportedSurfaces: ['canvas', 'allternit-canvas', 'design'],
  },
  {
    id: 'brand-guidelines',
    name: 'Brand Guidelines',
    source: 'anthropics/skills',
    description: 'Codify voice, visual system, and reusable brand constraints.',
    bucket: 'brand',
    priority: 'core',
    tags: ['brand', 'identity', 'guidelines'],
    capabilities: ['identity-system', 'brand-rules'],
    inputTypes: ['brief', 'existing-assets'],
    outputTypes: ['brand-system', 'guidelines'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'theme-factory',
    name: 'Theme Factory',
    source: 'anthropics/skills',
    description: 'Generate theme systems and visual variants for branded surfaces.',
    bucket: 'brand',
    priority: 'core',
    tags: ['themes', 'tokens', 'variants'],
    capabilities: ['theme-generation', 'visual-variants'],
    inputTypes: ['brief', 'references'],
    outputTypes: ['theme-system', 'style-variants'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'algorithmic-art',
    name: 'Algorithmic Art',
    source: 'anthropics/skills',
    description: 'Create repeatable generative visual systems and expressive branded graphics.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['generative', 'graphics', 'visual-systems'],
    capabilities: ['generative-assets', 'expressive-graphics'],
    inputTypes: ['prompt', 'references'],
    outputTypes: ['graphics', 'asset-pack'],
    supportedSurfaces: ['canvas', 'allternit-canvas'],
  },
  {
    id: 'brand',
    name: 'Brand',
    source: 'nextlevelbuilder/ui-ux-pro-max-skill',
    description: 'Brand and asset guidance for identities, banners, presentation visuals, and campaign direction.',
    bucket: 'brand',
    priority: 'core',
    tags: ['brand', 'assets', 'campaigns'],
    capabilities: ['brand-direction', 'asset-strategy'],
    inputTypes: ['brief', 'references', 'existing-assets'],
    outputTypes: ['brand-direction', 'asset-plan'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'banner-design',
    name: 'Banner Design',
    source: 'nextlevelbuilder/ui-ux-pro-max-skill',
    description: 'Produce banner, hero, and campaign visual treatments from a consistent brand system.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['banners', 'campaigns', 'heroes'],
    capabilities: ['campaign-visuals', 'hero-art-direction'],
    inputTypes: ['brief', 'references'],
    outputTypes: ['banners', 'hero-visuals'],
    supportedSurfaces: ['canvas', 'design'],
  },
  {
    id: 'fixing-motion-performance',
    name: 'Fixing Motion Performance',
    source: 'ibelick/ui-skills',
    description: 'Audit and repair janky motion, layout thrashing, and expensive animation patterns.',
    bucket: 'motion',
    priority: 'core',
    tags: ['motion', 'performance', 'animation'],
    capabilities: ['motion-audit', 'performance-fixes'],
    inputTypes: ['code', 'animation', 'screen'],
    outputTypes: ['performance-report', 'animation-fixes'],
    supportedSurfaces: ['design', 'code-skills', 'selection'],
  },
  {
    id: 'slides',
    name: 'Slides',
    source: 'nextlevelbuilder/ui-ux-pro-max-skill',
    description: 'Design slide narratives and media-rich presentation flows with clearer pacing and hierarchy.',
    bucket: 'motion',
    priority: 'core',
    tags: ['slides', 'presentations', 'storytelling'],
    capabilities: ['presentation-flow', 'narrative-pacing'],
    inputTypes: ['brief', 'content'],
    outputTypes: ['slide-direction', 'presentation-sequence'],
    supportedSurfaces: ['design', 'canvas', 'allternit-canvas'],
  },
  {
    id: 'pptx',
    name: 'PPTX',
    source: 'anthropics/skills',
    description: 'Create and edit presentation files as a structured media surface.',
    bucket: 'motion',
    priority: 'supporting',
    tags: ['pptx', 'presentations', 'exports'],
    capabilities: ['presentation-export', 'media-sequencing'],
    inputTypes: ['brief', 'content'],
    outputTypes: ['pptx-deck', 'presentation-structure'],
    supportedSurfaces: ['design', 'canvas', 'allternit-canvas'],
  },
  {
    id: 'slack-gif-creator',
    name: 'Slack GIF Creator',
    source: 'anthropics/skills',
    description: 'Generate compact animated media loops and shareable motion snippets.',
    bucket: 'motion',
    priority: 'supporting',
    tags: ['gif', 'animation', 'media'],
    capabilities: ['motion-snippets', 'shareable-loops'],
    inputTypes: ['screen', 'brief', 'content'],
    outputTypes: ['animated-gif', 'motion-assets'],
    supportedSurfaces: ['canvas', 'allternit-canvas'],
  },

  // ─── Huashu design philosophy schools ────────────────────────────────────────

  {
    id: 'hs-muji-hara',
    name: 'Muji / Kenya Hara — Emptiness (Ma)',
    source: 'alchaincyf/huashu-design',
    description: 'Extreme emptiness as a feature. No ornament, raw materials, negative space carries meaning. The Japanese concept of mu — the richness of nothing.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['japanese', 'minimal', 'emptiness', 'muji'],
    capabilities: ['visual-reduction', 'editorial-direction', 'identity-structure'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['brand-direction', 'style-direction'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-rams-braun',
    name: 'Braun / Dieter Rams — 10 Principles',
    source: 'alchaincyf/huashu-design',
    description: 'Good design is as little design as possible. Function before form, honest materials, long-lived objects. Apply the 10 principles: useful, honest, unobtrusive, long-lasting, thorough to the last detail.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['functionalism', 'braun', 'rams', 'industrial'],
    capabilities: ['product-direction', 'identity-structure', 'visual-reduction'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['brand-direction', 'style-direction'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-pentagram-bierut',
    name: 'Pentagram / Michael Bierut — Typography-First',
    source: 'alchaincyf/huashu-design',
    description: 'Extreme typographic hierarchy. Swiss grid discipline, black/white + one accent, 60%+ whitespace ratio. Let the type do the heavy lifting.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['pentagram', 'bierut', 'typography', 'swiss', 'grid'],
    capabilities: ['visual-philosophy', 'editorial-direction', 'identity-structure'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['brand-direction', 'style-direction'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-sagmeister-walsh',
    name: 'Sagmeister & Walsh — Emotional / Autobiographical',
    source: 'alchaincyf/huashu-design',
    description: 'Provocative, personal, handmade. Design as autobiography. Work that makes you feel something — discomfort, curiosity, joy. Nothing is off-limits if it serves the emotional argument.',
    bucket: 'brand',
    priority: 'specialized',
    tags: ['sagmeister', 'emotional', 'autobiographical', 'provocative'],
    capabilities: ['visual-attitude', 'editorial-direction', 'brand-personality'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['style-direction', 'brand-direction'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-vignelli-grid',
    name: 'Massimo Vignelli — Grid Discipline',
    source: 'alchaincyf/huashu-design',
    description: 'A few typefaces, a strong grid, and nothing else. Helvetica and Bodoni. The grid is not a prison; it is liberation from chaos. Semantic, structural, timeless.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['vignelli', 'grid', 'helvetica', 'modernist'],
    capabilities: ['editorial-composition', 'identity-structure', 'visual-philosophy'],
    inputTypes: ['brief', 'prompt'],
    outputTypes: ['brand-direction', 'style-direction'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-dumbar-systematic',
    name: 'Studio Dumbar — Systematic & Vibrant',
    source: 'alchaincyf/huashu-design',
    description: 'Geometric, multi-color systematic design. Data-driven composition, high-contrast palettes, municipal scale. Order that radiates energy rather than coldness.',
    bucket: 'brand',
    priority: 'specialized',
    tags: ['dumbar', 'systematic', 'vibrant', 'geometric'],
    capabilities: ['visual-philosophy', 'identity-structure', 'editorial-composition'],
    inputTypes: ['brief', 'references'],
    outputTypes: ['brand-direction', 'visual-assets'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-jetset-selfreferential',
    name: 'Experimental Jetset — Self-Reference',
    source: 'alchaincyf/huashu-design',
    description: 'Design about design. Helvetica, deconstructed systems, monochrome with deliberate ruptures. The design refers to its own making — the process is visible.',
    bucket: 'brand',
    priority: 'specialized',
    tags: ['jetset', 'self-reference', 'helvetica', 'monochrome'],
    capabilities: ['visual-philosophy', 'editorial-direction', 'identity-structure'],
    inputTypes: ['brief', 'prompt'],
    outputTypes: ['style-direction', 'brand-direction'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-norm-mathematical',
    name: 'Norm (Swiss) — Mathematical Proportion',
    source: 'alchaincyf/huashu-design',
    description: 'Mathematical rhythm, proportional systems, neutral precision. Every spacing decision follows a rule. Swiss discipline at its most rigorous and unsentimental.',
    bucket: 'brand',
    priority: 'specialized',
    tags: ['norm', 'swiss', 'mathematical', 'proportion'],
    capabilities: ['visual-philosophy', 'editorial-composition', 'identity-structure'],
    inputTypes: ['brief', 'prompt'],
    outputTypes: ['style-direction'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-borsche-editorial',
    name: 'Bureau Borsche — Editorial Fashion Direction',
    source: 'alchaincyf/huashu-design',
    description: 'High-fashion editorial sensibility. Photography-forward, bold crop, contrasting type weight, magazine culture. Borsche treats cultural institutions like luxury brands.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['borsche', 'editorial', 'fashion', 'photography'],
    capabilities: ['editorial-direction', 'visual-philosophy', 'asset-creation'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['brand-direction', 'editorial-assets'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-hort-raw',
    name: 'Hort — Raw Typography / Collage',
    source: 'alchaincyf/huashu-design',
    description: 'Cut-up typography, collage aesthetics, Berlin underground energy. Anti-polish as a stance. Rough edges, unexpected juxtapositions, cultural urgency.',
    bucket: 'brand',
    priority: 'specialized',
    tags: ['hort', 'collage', 'raw', 'typography'],
    capabilities: ['visual-attitude', 'editorial-direction', 'graphic-direction'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['style-direction', 'visual-assets'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-wolff-olins',
    name: 'Wolff Olins — Brand Transformation',
    source: 'alchaincyf/huashu-design',
    description: 'Bold, unexpected, high contrast. Brands as vehicles for organizational change. Provocative identity systems designed to scale across complexity.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['wolff-olins', 'transformation', 'identity', 'bold'],
    capabilities: ['identity-direction', 'brand-personality', 'visual-philosophy'],
    inputTypes: ['brief', 'references'],
    outputTypes: ['brand-direction', 'identity-extension'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-nonformat-phototypo',
    name: 'Non-Format — Photo-Led Typography',
    source: 'alchaincyf/huashu-design',
    description: 'Photography and typographic freedom in tension. Collage, cut-up, surreal combinations. Music and arts culture. Unexpected hierarchy that rewards close looking.',
    bucket: 'brand',
    priority: 'specialized',
    tags: ['non-format', 'photography', 'typographic-freedom', 'collage'],
    capabilities: ['editorial-direction', 'visual-attitude', 'graphic-direction'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['style-direction', 'visual-assets'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-bibliotheque-neutral',
    name: 'Bibliothèque — Neutral Systems',
    source: 'alchaincyf/huashu-design',
    description: 'Swiss discipline at its most detail-obsessed. Neutral tone, systems thinking, micro-craft. Nothing expressive — only precise. The grid is the message.',
    bucket: 'brand',
    priority: 'specialized',
    tags: ['bibliotheque', 'neutral', 'systems', 'swiss'],
    capabilities: ['identity-structure', 'editorial-composition', 'visual-philosophy'],
    inputTypes: ['brief', 'prompt'],
    outputTypes: ['style-direction', 'brand-direction'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-base-conceptual',
    name: 'Base Design — Conceptual Editorial',
    source: 'alchaincyf/huashu-design',
    description: 'Strong typography, confident whitespace, conceptual rigor. The idea drives the form. Cultural institutions, arts clients, luxury brands. Intelligence as aesthetic.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['base', 'conceptual', 'editorial', 'typography'],
    capabilities: ['editorial-direction', 'identity-structure', 'visual-philosophy'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['brand-direction', 'style-direction'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-build-restrained',
    name: 'Build — Grid-Based Restraint',
    source: 'alchaincyf/huashu-design',
    description: 'Grid-based, typographically minimal, refined. Every decision deliberate and documented. Build treats design as architecture — structural, loadbearing, exposed.',
    bucket: 'brand',
    priority: 'specialized',
    tags: ['build', 'grid', 'typographic-minimalism', 'structured'],
    capabilities: ['identity-structure', 'editorial-composition', 'visual-reduction'],
    inputTypes: ['brief', 'prompt'],
    outputTypes: ['style-direction', 'brand-direction'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-feixen-playful',
    name: 'Studio Feixen — Flat Playful',
    source: 'alchaincyf/huashu-design',
    description: 'Flat, illustrative, bold color-fields, joyful visual thinking. Swiss training with a cheeky attitude. Characters and scenes from simple geometric shapes.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['feixen', 'flat', 'illustrative', 'playful'],
    capabilities: ['visual-attitude', 'asset-creation', 'brand-personality'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['visual-assets', 'style-direction'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-snask-bold',
    name: 'Snask — Bold Color / Cheeky',
    source: 'alchaincyf/huashu-design',
    description: 'Bright, loud, playful with serious attitude. Primary palettes pushed to extremes, vintage inspiration, unapologetic personality.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['snask', 'bold', 'color', 'playful'],
    capabilities: ['brand-personality', 'visual-attitude', 'graphic-direction'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['brand-direction', 'style-direction'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-spin-identity-arch',
    name: 'Spin — Identity Architecture',
    source: 'alchaincyf/huashu-design',
    description: 'Systems-thinking for brand identity. Detail-oriented, structured, scaled. Spin builds identity as infrastructure — modules that flex without losing coherence.',
    bucket: 'brand',
    priority: 'specialized',
    tags: ['spin', 'identity', 'systematic', 'modular'],
    capabilities: ['identity-direction', 'identity-structure', 'visual-philosophy'],
    inputTypes: ['brief', 'references'],
    outputTypes: ['identity-extension', 'brand-direction'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-2x4-information',
    name: '2x4 — Information Design',
    source: 'alchaincyf/huashu-design',
    description: 'Photo-led, minimal text, editorial precision. Cultural institutions, fashion houses, archives. The image carries the argument.',
    bucket: 'brand',
    priority: 'specialized',
    tags: ['2x4', 'information-design', 'editorial', 'photography'],
    capabilities: ['editorial-direction', 'identity-structure', 'visual-philosophy'],
    inputTypes: ['brief', 'references', 'content'],
    outputTypes: ['editorial-assets', 'brand-direction'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-why-not-expressive',
    name: 'Why Not Associates — Expressive Typography',
    source: 'alchaincyf/huashu-design',
    description: 'Typography as image. Expressive, collaged, energetic layouts where letterforms are the illustration. Cultural, music, arts work. Post-punk visual energy.',
    bucket: 'brand',
    priority: 'specialized',
    tags: ['why-not', 'expressive', 'typography', 'collage'],
    capabilities: ['graphic-direction', 'editorial-direction', 'visual-attitude'],
    inputTypes: ['brief', 'references', 'prompt'],
    outputTypes: ['style-direction', 'visual-assets'],
    supportedSurfaces: ['design', 'canvas'],
  },

  // ─── Huashu scene templates ───────────────────────────────────────────────────

  {
    id: 'hs-tpl-landing',
    name: 'Landing Page',
    source: 'alchaincyf/huashu-design',
    description: 'Hero-first marketing landing page with above-fold hook, features section, social proof, and conversion CTA. Fully responsive, 3 breakpoints.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['landing', 'marketing', 'hero', 'responsive'],
    capabilities: ['marketing-page', 'conversion-design', 'brand-direction'],
    inputTypes: ['brief', 'content', 'prompt'],
    outputTypes: ['landing-page', 'marketing-assets'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-tpl-dashboard',
    name: 'SaaS Dashboard',
    source: 'alchaincyf/huashu-design',
    description: 'Analytics dashboard with sidebar nav, KPI cards, chart area, table, and status panel. Built for dense data with strong hierarchy.',
    bucket: 'frontend',
    priority: 'supporting',
    tags: ['dashboard', 'saas', 'analytics', 'data-viz'],
    capabilities: ['dashboard-design', 'data-visualization', 'surface-hierarchy'],
    inputTypes: ['brief', 'data-schema', 'prompt'],
    outputTypes: ['dashboard-layout', 'interface-spec'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-tpl-pitch-deck',
    name: 'Pitch Deck',
    source: 'alchaincyf/huashu-design',
    description: 'Investor-facing slide deck with problem/solution/market/traction/ask structure. Fixed canvas, navigation, PDF export, slide counter.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['pitch', 'slides', 'investor', 'deck'],
    capabilities: ['presentation-visuals', 'slide-assets', 'brand-direction'],
    inputTypes: ['brief', 'content', 'prompt'],
    outputTypes: ['slide-deck'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-tpl-mobile-app',
    name: 'Mobile App Screens',
    source: 'alchaincyf/huashu-design',
    description: 'Multi-screen mobile app prototype with onboarding, home, detail, and profile screens. Rendered in iOS/Android device frames.',
    bucket: 'frontend',
    priority: 'supporting',
    tags: ['mobile', 'ios', 'android', 'app', 'screens'],
    capabilities: ['mobile-design', 'screen-flow', 'interaction-design'],
    inputTypes: ['brief', 'flow', 'prompt'],
    outputTypes: ['mobile-screens', 'screen-spec'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-tpl-editorial',
    name: 'Editorial Article',
    source: 'alchaincyf/huashu-design',
    description: 'Long-form editorial with pull quotes, image breaks, dropcap, sidebar annotations, and reading-progress indicator. Pairs a display face with a body face.',
    bucket: 'frontend',
    priority: 'supporting',
    tags: ['editorial', 'article', 'typography', 'reading'],
    capabilities: ['editorial-composition', 'typographic-direction', 'layout-refinement'],
    inputTypes: ['content', 'brief', 'prompt'],
    outputTypes: ['editorial-layout'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-tpl-social-card',
    name: 'Social Media Card',
    source: 'alchaincyf/huashu-design',
    description: 'Fixed-canvas social visuals for 1:1, 16:9, and 9:16 Stories. Export-ready, brand tokens applied, consistent identity across sizes.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['social', 'card', 'og-image', 'campaign'],
    capabilities: ['campaign-visuals', 'asset-creation', 'brand-direction'],
    inputTypes: ['brief', 'content', 'brand-tokens'],
    outputTypes: ['social-assets', 'campaign-graphics'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
  {
    id: 'hs-tpl-email',
    name: 'Email Newsletter',
    source: 'alchaincyf/huashu-design',
    description: 'HTML email with header, hero image, text block, CTA button, and footer. Table-based layout for client compatibility. Inline CSS, dark mode support.',
    bucket: 'frontend',
    priority: 'specialized',
    tags: ['email', 'newsletter', 'html-email', 'campaign'],
    capabilities: ['email-design', 'campaign-visuals'],
    inputTypes: ['brief', 'content'],
    outputTypes: ['email-template'],
    supportedSurfaces: ['design', 'canvas'],
  },
  {
    id: 'hs-tpl-product-showcase',
    name: 'Product Showcase Page',
    source: 'alchaincyf/huashu-design',
    description: 'Scrollytelling product marketing page with sticky header, animated feature reveals, device mockups, testimonials, and pricing grid.',
    bucket: 'brand',
    priority: 'supporting',
    tags: ['product', 'marketing', 'scrollytelling', 'showcase'],
    capabilities: ['marketing-page', 'brand-direction', 'interaction-design'],
    inputTypes: ['brief', 'content', 'prompt'],
    outputTypes: ['product-page', 'marketing-assets'],
    supportedSurfaces: ['design', 'canvas', 'marketplace'],
  },
];
